#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 93
#define LARGE_STATE_COUNT 11
#define SYMBOL_COUNT 36
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_let = 1,
  anon_sym_EQ = 2,
  anon_sym_STAR = 3,
  anon_sym_PLUS = 4,
  anon_sym_LPAREN = 5,
  anon_sym_RPAREN = 6,
  anon_sym_fn = 7,
  anon_sym_LBRACE = 8,
  anon_sym_RBRACE = 9,
  anon_sym_COMMA = 10,
  anon_sym_return = 11,
  anon_sym_DASH = 12,
  anon_sym_BANG = 13,
  sym_number = 14,
  sym_boolean = 15,
  sym_identifier = 16,
  sym_source_file = 17,
  sym__statement = 18,
  sym_let_statement = 19,
  sym__expression = 20,
  sym_binary_expression = 21,
  sym__grouped_expression = 22,
  sym_function = 23,
  sym_parameters = 24,
  aux_sym__parameter_list = 25,
  aux_sym__statement_list = 26,
  sym_block = 27,
  sym__parameter = 28,
  sym_return_statement = 29,
  sym_function_call = 30,
  sym_arguments = 31,
  aux_sym__argument_list = 32,
  sym__argument = 33,
  sym_unary_expression = 34,
  aux_sym_source_file_repeat1 = 35,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_STAR] = "*",
  [anon_sym_PLUS] = "+",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_fn] = "fn",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COMMA] = ",",
  [anon_sym_return] = "return",
  [anon_sym_DASH] = "-",
  [anon_sym_BANG] = "!",
  [sym_number] = "number",
  [sym_boolean] = "boolean",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_let_statement] = "let_statement",
  [sym__expression] = "_expression",
  [sym_binary_expression] = "binary_expression",
  [sym__grouped_expression] = "_grouped_expression",
  [sym_function] = "function",
  [sym_parameters] = "parameters",
  [aux_sym__parameter_list] = "_parameter_list",
  [aux_sym__statement_list] = "_statement_list",
  [sym_block] = "block",
  [sym__parameter] = "_parameter",
  [sym_return_statement] = "return_statement",
  [sym_function_call] = "function_call",
  [sym_arguments] = "arguments",
  [aux_sym__argument_list] = "_argument_list",
  [sym__argument] = "_argument",
  [sym_unary_expression] = "unary_expression",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_BANG] = anon_sym_BANG,
  [sym_number] = sym_number,
  [sym_boolean] = sym_boolean,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_let_statement] = sym_let_statement,
  [sym__expression] = sym__expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym__grouped_expression] = sym__grouped_expression,
  [sym_function] = sym_function,
  [sym_parameters] = sym_parameters,
  [aux_sym__parameter_list] = aux_sym__parameter_list,
  [aux_sym__statement_list] = aux_sym__statement_list,
  [sym_block] = sym_block,
  [sym__parameter] = sym__parameter,
  [sym_return_statement] = sym_return_statement,
  [sym_function_call] = sym_function_call,
  [sym_arguments] = sym_arguments,
  [aux_sym__argument_list] = aux_sym__argument_list,
  [sym__argument] = sym__argument,
  [sym_unary_expression] = sym_unary_expression,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_let_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__grouped_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_parameters] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__parameter_list] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__statement_list] = {
    .visible = false,
    .named = false,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym__parameter] = {
    .visible = false,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_arguments] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__argument_list] = {
    .visible = false,
    .named = false,
  },
  [sym__argument] = {
    .visible = false,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 2,
  [7] = 5,
  [8] = 2,
  [9] = 9,
  [10] = 5,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 12,
  [15] = 12,
  [16] = 11,
  [17] = 11,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 21,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 26,
  [32] = 32,
  [33] = 33,
  [34] = 21,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 35,
  [39] = 18,
  [40] = 40,
  [41] = 23,
  [42] = 42,
  [43] = 23,
  [44] = 32,
  [45] = 29,
  [46] = 19,
  [47] = 28,
  [48] = 26,
  [49] = 24,
  [50] = 33,
  [51] = 20,
  [52] = 28,
  [53] = 37,
  [54] = 36,
  [55] = 55,
  [56] = 18,
  [57] = 42,
  [58] = 40,
  [59] = 30,
  [60] = 20,
  [61] = 27,
  [62] = 19,
  [63] = 25,
  [64] = 42,
  [65] = 30,
  [66] = 27,
  [67] = 36,
  [68] = 40,
  [69] = 37,
  [70] = 25,
  [71] = 71,
  [72] = 72,
  [73] = 72,
  [74] = 72,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 79,
  [82] = 79,
  [83] = 83,
  [84] = 83,
  [85] = 83,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 88,
  [91] = 86,
  [92] = 92,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      if (lookahead == '!') ADVANCE(16);
      if (lookahead == '(') ADVANCE(8);
      if (lookahead == ')') ADVANCE(9);
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '+') ADVANCE(7);
      if (lookahead == ',') ADVANCE(13);
      if (lookahead == '-') ADVANCE(15);
      if (lookahead == '=') ADVANCE(5);
      if (lookahead == 'f') ADVANCE(19);
      if (lookahead == 'l') ADVANCE(20);
      if (lookahead == 'r') ADVANCE(22);
      if (lookahead == 't') ADVANCE(25);
      if (lookahead == '{') ADVANCE(11);
      if (lookahead == '}') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(16);
      if (lookahead == '(') ADVANCE(8);
      if (lookahead == ')') ADVANCE(9);
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '+') ADVANCE(7);
      if (lookahead == ',') ADVANCE(13);
      if (lookahead == '-') ADVANCE(15);
      if (lookahead == 'f') ADVANCE(19);
      if (lookahead == 't') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 2:
      if (lookahead == ')') ADVANCE(9);
      if (lookahead == ',') ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_let);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_fn);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_return);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_boolean);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(23);
      if (lookahead == 'n') ADVANCE(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(18);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(29);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(27);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(14);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(30);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(24);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(21);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(31);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(21);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 2},
  [76] = {.lex_state = 2},
  [77] = {.lex_state = 2},
  [78] = {.lex_state = 2},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 2},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 2},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 2},
  [92] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_boolean] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(92),
    [sym__statement] = STATE(9),
    [sym_let_statement] = STATE(9),
    [sym__expression] = STATE(32),
    [sym_binary_expression] = STATE(32),
    [sym__grouped_expression] = STATE(32),
    [sym_function] = STATE(32),
    [sym_return_statement] = STATE(9),
    [sym_function_call] = STATE(32),
    [sym_unary_expression] = STATE(32),
    [aux_sym_source_file_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_let] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(13),
    [sym_number] = ACTIONS(15),
    [sym_boolean] = ACTIONS(17),
    [sym_identifier] = ACTIONS(17),
  },
  [2] = {
    [sym__statement] = STATE(7),
    [sym_let_statement] = STATE(7),
    [sym__expression] = STATE(44),
    [sym_binary_expression] = STATE(44),
    [sym__grouped_expression] = STATE(44),
    [sym_function] = STATE(44),
    [aux_sym__statement_list] = STATE(7),
    [sym_return_statement] = STATE(7),
    [sym_function_call] = STATE(44),
    [sym_unary_expression] = STATE(44),
    [anon_sym_let] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_fn] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(25),
    [anon_sym_return] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_BANG] = ACTIONS(29),
    [sym_number] = ACTIONS(31),
    [sym_boolean] = ACTIONS(33),
    [sym_identifier] = ACTIONS(33),
  },
  [3] = {
    [sym__statement] = STATE(3),
    [sym_let_statement] = STATE(3),
    [sym__expression] = STATE(44),
    [sym_binary_expression] = STATE(44),
    [sym__grouped_expression] = STATE(44),
    [sym_function] = STATE(44),
    [aux_sym__statement_list] = STATE(3),
    [sym_return_statement] = STATE(3),
    [sym_function_call] = STATE(44),
    [sym_unary_expression] = STATE(44),
    [anon_sym_let] = ACTIONS(35),
    [anon_sym_LPAREN] = ACTIONS(38),
    [anon_sym_fn] = ACTIONS(41),
    [anon_sym_RBRACE] = ACTIONS(44),
    [anon_sym_return] = ACTIONS(46),
    [anon_sym_DASH] = ACTIONS(49),
    [anon_sym_BANG] = ACTIONS(49),
    [sym_number] = ACTIONS(52),
    [sym_boolean] = ACTIONS(55),
    [sym_identifier] = ACTIONS(55),
  },
  [4] = {
    [sym__statement] = STATE(4),
    [sym_let_statement] = STATE(4),
    [sym__expression] = STATE(32),
    [sym_binary_expression] = STATE(32),
    [sym__grouped_expression] = STATE(32),
    [sym_function] = STATE(32),
    [sym_return_statement] = STATE(4),
    [sym_function_call] = STATE(32),
    [sym_unary_expression] = STATE(32),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(58),
    [anon_sym_let] = ACTIONS(60),
    [anon_sym_LPAREN] = ACTIONS(63),
    [anon_sym_fn] = ACTIONS(66),
    [anon_sym_return] = ACTIONS(69),
    [anon_sym_DASH] = ACTIONS(72),
    [anon_sym_BANG] = ACTIONS(72),
    [sym_number] = ACTIONS(75),
    [sym_boolean] = ACTIONS(78),
    [sym_identifier] = ACTIONS(78),
  },
  [5] = {
    [sym__statement] = STATE(3),
    [sym_let_statement] = STATE(3),
    [sym__expression] = STATE(44),
    [sym_binary_expression] = STATE(44),
    [sym__grouped_expression] = STATE(44),
    [sym_function] = STATE(44),
    [aux_sym__statement_list] = STATE(3),
    [sym_return_statement] = STATE(3),
    [sym_function_call] = STATE(44),
    [sym_unary_expression] = STATE(44),
    [anon_sym_let] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_fn] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(81),
    [anon_sym_return] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_BANG] = ACTIONS(29),
    [sym_number] = ACTIONS(31),
    [sym_boolean] = ACTIONS(33),
    [sym_identifier] = ACTIONS(33),
  },
  [6] = {
    [sym__statement] = STATE(10),
    [sym_let_statement] = STATE(10),
    [sym__expression] = STATE(44),
    [sym_binary_expression] = STATE(44),
    [sym__grouped_expression] = STATE(44),
    [sym_function] = STATE(44),
    [aux_sym__statement_list] = STATE(10),
    [sym_return_statement] = STATE(10),
    [sym_function_call] = STATE(44),
    [sym_unary_expression] = STATE(44),
    [anon_sym_let] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_fn] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(83),
    [anon_sym_return] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_BANG] = ACTIONS(29),
    [sym_number] = ACTIONS(31),
    [sym_boolean] = ACTIONS(33),
    [sym_identifier] = ACTIONS(33),
  },
  [7] = {
    [sym__statement] = STATE(3),
    [sym_let_statement] = STATE(3),
    [sym__expression] = STATE(44),
    [sym_binary_expression] = STATE(44),
    [sym__grouped_expression] = STATE(44),
    [sym_function] = STATE(44),
    [aux_sym__statement_list] = STATE(3),
    [sym_return_statement] = STATE(3),
    [sym_function_call] = STATE(44),
    [sym_unary_expression] = STATE(44),
    [anon_sym_let] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_fn] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(85),
    [anon_sym_return] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_BANG] = ACTIONS(29),
    [sym_number] = ACTIONS(31),
    [sym_boolean] = ACTIONS(33),
    [sym_identifier] = ACTIONS(33),
  },
  [8] = {
    [sym__statement] = STATE(5),
    [sym_let_statement] = STATE(5),
    [sym__expression] = STATE(44),
    [sym_binary_expression] = STATE(44),
    [sym__grouped_expression] = STATE(44),
    [sym_function] = STATE(44),
    [aux_sym__statement_list] = STATE(5),
    [sym_return_statement] = STATE(5),
    [sym_function_call] = STATE(44),
    [sym_unary_expression] = STATE(44),
    [anon_sym_let] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_fn] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(87),
    [anon_sym_return] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_BANG] = ACTIONS(29),
    [sym_number] = ACTIONS(31),
    [sym_boolean] = ACTIONS(33),
    [sym_identifier] = ACTIONS(33),
  },
  [9] = {
    [sym__statement] = STATE(4),
    [sym_let_statement] = STATE(4),
    [sym__expression] = STATE(32),
    [sym_binary_expression] = STATE(32),
    [sym__grouped_expression] = STATE(32),
    [sym_function] = STATE(32),
    [sym_return_statement] = STATE(4),
    [sym_function_call] = STATE(32),
    [sym_unary_expression] = STATE(32),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(89),
    [anon_sym_let] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [anon_sym_BANG] = ACTIONS(13),
    [sym_number] = ACTIONS(15),
    [sym_boolean] = ACTIONS(17),
    [sym_identifier] = ACTIONS(17),
  },
  [10] = {
    [sym__statement] = STATE(3),
    [sym_let_statement] = STATE(3),
    [sym__expression] = STATE(44),
    [sym_binary_expression] = STATE(44),
    [sym__grouped_expression] = STATE(44),
    [sym_function] = STATE(44),
    [aux_sym__statement_list] = STATE(3),
    [sym_return_statement] = STATE(3),
    [sym_function_call] = STATE(44),
    [sym_unary_expression] = STATE(44),
    [anon_sym_let] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_fn] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(91),
    [anon_sym_return] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_BANG] = ACTIONS(29),
    [sym_number] = ACTIONS(31),
    [sym_boolean] = ACTIONS(33),
    [sym_identifier] = ACTIONS(33),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      anon_sym_RPAREN,
    ACTIONS(97), 1,
      anon_sym_fn,
    ACTIONS(101), 1,
      sym_number,
    ACTIONS(99), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(103), 2,
      sym_boolean,
      sym_identifier,
    STATE(13), 2,
      aux_sym__argument_list,
      sym__argument,
    STATE(55), 6,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_unary_expression,
  [33] = 8,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(97), 1,
      anon_sym_fn,
    ACTIONS(101), 1,
      sym_number,
    ACTIONS(105), 1,
      anon_sym_RPAREN,
    ACTIONS(99), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(103), 2,
      sym_boolean,
      sym_identifier,
    STATE(11), 2,
      aux_sym__argument_list,
      sym__argument,
    STATE(55), 6,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_unary_expression,
  [66] = 8,
    ACTIONS(107), 1,
      anon_sym_LPAREN,
    ACTIONS(110), 1,
      anon_sym_RPAREN,
    ACTIONS(112), 1,
      anon_sym_fn,
    ACTIONS(118), 1,
      sym_number,
    ACTIONS(115), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(121), 2,
      sym_boolean,
      sym_identifier,
    STATE(13), 2,
      aux_sym__argument_list,
      sym__argument,
    STATE(55), 6,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_unary_expression,
  [99] = 8,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(97), 1,
      anon_sym_fn,
    ACTIONS(101), 1,
      sym_number,
    ACTIONS(124), 1,
      anon_sym_RPAREN,
    ACTIONS(99), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(103), 2,
      sym_boolean,
      sym_identifier,
    STATE(16), 2,
      aux_sym__argument_list,
      sym__argument,
    STATE(55), 6,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_unary_expression,
  [132] = 8,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(97), 1,
      anon_sym_fn,
    ACTIONS(101), 1,
      sym_number,
    ACTIONS(126), 1,
      anon_sym_RPAREN,
    ACTIONS(99), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(103), 2,
      sym_boolean,
      sym_identifier,
    STATE(17), 2,
      aux_sym__argument_list,
      sym__argument,
    STATE(55), 6,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_unary_expression,
  [165] = 8,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(97), 1,
      anon_sym_fn,
    ACTIONS(101), 1,
      sym_number,
    ACTIONS(128), 1,
      anon_sym_RPAREN,
    ACTIONS(99), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(103), 2,
      sym_boolean,
      sym_identifier,
    STATE(13), 2,
      aux_sym__argument_list,
      sym__argument,
    STATE(55), 6,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_unary_expression,
  [198] = 8,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(97), 1,
      anon_sym_fn,
    ACTIONS(101), 1,
      sym_number,
    ACTIONS(130), 1,
      anon_sym_RPAREN,
    ACTIONS(99), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(103), 2,
      sym_boolean,
      sym_identifier,
    STATE(13), 2,
      aux_sym__argument_list,
      sym__argument,
    STATE(55), 6,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_unary_expression,
  [231] = 5,
    ACTIONS(136), 1,
      anon_sym_STAR,
    ACTIONS(138), 1,
      anon_sym_LPAREN,
    STATE(25), 1,
      sym_arguments,
    ACTIONS(134), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(132), 6,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [256] = 4,
    ACTIONS(138), 1,
      anon_sym_LPAREN,
    STATE(25), 1,
      sym_arguments,
    ACTIONS(134), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(132), 7,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [279] = 4,
    ACTIONS(138), 1,
      anon_sym_LPAREN,
    STATE(25), 1,
      sym_arguments,
    ACTIONS(142), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(140), 7,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [302] = 6,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_fn,
    ACTIONS(144), 1,
      sym_number,
    ACTIONS(29), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(146), 2,
      sym_boolean,
      sym_identifier,
    STATE(51), 6,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_unary_expression,
  [328] = 6,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(148), 1,
      sym_number,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(150), 2,
      sym_boolean,
      sym_identifier,
    STATE(20), 6,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_unary_expression,
  [354] = 6,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(152), 1,
      sym_number,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(154), 2,
      sym_boolean,
      sym_identifier,
    STATE(74), 6,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_unary_expression,
  [380] = 6,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(156), 1,
      sym_number,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(158), 2,
      sym_boolean,
      sym_identifier,
    STATE(33), 6,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_unary_expression,
  [406] = 2,
    ACTIONS(162), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(160), 8,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [424] = 6,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(164), 1,
      sym_number,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(166), 2,
      sym_boolean,
      sym_identifier,
    STATE(18), 6,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_unary_expression,
  [450] = 2,
    ACTIONS(170), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(168), 8,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [468] = 6,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(172), 1,
      sym_number,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(174), 2,
      sym_boolean,
      sym_identifier,
    STATE(19), 6,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_unary_expression,
  [494] = 6,
    ACTIONS(136), 1,
      anon_sym_STAR,
    ACTIONS(138), 1,
      anon_sym_LPAREN,
    ACTIONS(180), 1,
      anon_sym_PLUS,
    STATE(25), 1,
      sym_arguments,
    ACTIONS(176), 4,
      ts_builtin_sym_end,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
    ACTIONS(178), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
  [520] = 2,
    ACTIONS(184), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(182), 8,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [538] = 6,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_fn,
    ACTIONS(186), 1,
      sym_number,
    ACTIONS(29), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(188), 2,
      sym_boolean,
      sym_identifier,
    STATE(39), 6,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_unary_expression,
  [564] = 6,
    ACTIONS(136), 1,
      anon_sym_STAR,
    ACTIONS(138), 1,
      anon_sym_LPAREN,
    ACTIONS(180), 1,
      anon_sym_PLUS,
    STATE(25), 1,
      sym_arguments,
    ACTIONS(190), 4,
      ts_builtin_sym_end,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
    ACTIONS(192), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
  [590] = 6,
    ACTIONS(136), 1,
      anon_sym_STAR,
    ACTIONS(138), 1,
      anon_sym_LPAREN,
    ACTIONS(180), 1,
      anon_sym_PLUS,
    STATE(25), 1,
      sym_arguments,
    ACTIONS(194), 4,
      ts_builtin_sym_end,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
    ACTIONS(196), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
  [616] = 6,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(97), 1,
      anon_sym_fn,
    ACTIONS(198), 1,
      sym_number,
    ACTIONS(99), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(200), 2,
      sym_boolean,
      sym_identifier,
    STATE(60), 6,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_unary_expression,
  [642] = 6,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_fn,
    ACTIONS(202), 1,
      sym_number,
    ACTIONS(29), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(204), 2,
      sym_boolean,
      sym_identifier,
    STATE(45), 6,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_unary_expression,
  [668] = 2,
    ACTIONS(208), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(206), 8,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [686] = 2,
    ACTIONS(212), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(210), 8,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [704] = 6,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(214), 1,
      sym_number,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(216), 2,
      sym_boolean,
      sym_identifier,
    STATE(29), 6,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_unary_expression,
  [730] = 5,
    ACTIONS(218), 1,
      anon_sym_STAR,
    ACTIONS(220), 1,
      anon_sym_LPAREN,
    STATE(63), 1,
      sym_arguments,
    ACTIONS(132), 5,
      anon_sym_PLUS,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
    ACTIONS(134), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
  [754] = 2,
    ACTIONS(224), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(222), 8,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [772] = 6,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(226), 1,
      sym_number,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(228), 2,
      sym_boolean,
      sym_identifier,
    STATE(73), 6,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_unary_expression,
  [798] = 2,
    ACTIONS(232), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(230), 8,
      ts_builtin_sym_end,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [816] = 6,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(234), 1,
      sym_number,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(236), 2,
      sym_boolean,
      sym_identifier,
    STATE(72), 6,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_unary_expression,
  [842] = 6,
    ACTIONS(218), 1,
      anon_sym_STAR,
    ACTIONS(220), 1,
      anon_sym_LPAREN,
    ACTIONS(238), 1,
      anon_sym_PLUS,
    STATE(63), 1,
      sym_arguments,
    ACTIONS(190), 4,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
    ACTIONS(192), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
  [868] = 6,
    ACTIONS(218), 1,
      anon_sym_STAR,
    ACTIONS(220), 1,
      anon_sym_LPAREN,
    ACTIONS(238), 1,
      anon_sym_PLUS,
    STATE(63), 1,
      sym_arguments,
    ACTIONS(176), 4,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
    ACTIONS(178), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
  [894] = 4,
    ACTIONS(220), 1,
      anon_sym_LPAREN,
    STATE(63), 1,
      sym_arguments,
    ACTIONS(134), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(132), 6,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [916] = 6,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(97), 1,
      anon_sym_fn,
    ACTIONS(240), 1,
      sym_number,
    ACTIONS(99), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(242), 2,
      sym_boolean,
      sym_identifier,
    STATE(62), 6,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_unary_expression,
  [942] = 6,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(97), 1,
      anon_sym_fn,
    ACTIONS(244), 1,
      sym_number,
    ACTIONS(99), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(246), 2,
      sym_boolean,
      sym_identifier,
    STATE(56), 6,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_unary_expression,
  [968] = 6,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_fn,
    ACTIONS(248), 1,
      sym_number,
    ACTIONS(29), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(250), 2,
      sym_boolean,
      sym_identifier,
    STATE(50), 6,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_unary_expression,
  [994] = 6,
    ACTIONS(218), 1,
      anon_sym_STAR,
    ACTIONS(220), 1,
      anon_sym_LPAREN,
    ACTIONS(238), 1,
      anon_sym_PLUS,
    STATE(63), 1,
      sym_arguments,
    ACTIONS(194), 4,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
    ACTIONS(196), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
  [1020] = 4,
    ACTIONS(220), 1,
      anon_sym_LPAREN,
    STATE(63), 1,
      sym_arguments,
    ACTIONS(142), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(140), 6,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1042] = 6,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_fn,
    ACTIONS(252), 1,
      sym_number,
    ACTIONS(29), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(254), 2,
      sym_boolean,
      sym_identifier,
    STATE(46), 6,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_unary_expression,
  [1068] = 2,
    ACTIONS(212), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(210), 7,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1085] = 2,
    ACTIONS(208), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(206), 7,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1102] = 7,
    ACTIONS(256), 1,
      anon_sym_STAR,
    ACTIONS(258), 1,
      anon_sym_PLUS,
    ACTIONS(260), 1,
      anon_sym_LPAREN,
    ACTIONS(266), 1,
      anon_sym_COMMA,
    STATE(70), 1,
      sym_arguments,
    ACTIONS(264), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(262), 4,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1129] = 5,
    ACTIONS(256), 1,
      anon_sym_STAR,
    ACTIONS(260), 1,
      anon_sym_LPAREN,
    STATE(70), 1,
      sym_arguments,
    ACTIONS(134), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(132), 6,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1152] = 2,
    ACTIONS(232), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(230), 7,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1169] = 2,
    ACTIONS(224), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(222), 7,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1186] = 2,
    ACTIONS(184), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(182), 7,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1203] = 4,
    ACTIONS(260), 1,
      anon_sym_LPAREN,
    STATE(70), 1,
      sym_arguments,
    ACTIONS(142), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(140), 7,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1224] = 2,
    ACTIONS(170), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(168), 7,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1241] = 4,
    ACTIONS(260), 1,
      anon_sym_LPAREN,
    STATE(70), 1,
      sym_arguments,
    ACTIONS(134), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(132), 7,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1262] = 2,
    ACTIONS(162), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(160), 7,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1279] = 2,
    ACTIONS(232), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(230), 8,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1295] = 2,
    ACTIONS(184), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(182), 8,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1311] = 2,
    ACTIONS(170), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(168), 8,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1327] = 2,
    ACTIONS(208), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(206), 8,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1343] = 2,
    ACTIONS(224), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(222), 8,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1359] = 2,
    ACTIONS(212), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(210), 8,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1375] = 2,
    ACTIONS(162), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(160), 8,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1391] = 2,
    ACTIONS(270), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(268), 5,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1404] = 5,
    ACTIONS(136), 1,
      anon_sym_STAR,
    ACTIONS(138), 1,
      anon_sym_LPAREN,
    ACTIONS(180), 1,
      anon_sym_PLUS,
    ACTIONS(272), 1,
      anon_sym_RPAREN,
    STATE(25), 1,
      sym_arguments,
  [1420] = 5,
    ACTIONS(136), 1,
      anon_sym_STAR,
    ACTIONS(138), 1,
      anon_sym_LPAREN,
    ACTIONS(180), 1,
      anon_sym_PLUS,
    ACTIONS(274), 1,
      anon_sym_RPAREN,
    STATE(25), 1,
      sym_arguments,
  [1436] = 5,
    ACTIONS(136), 1,
      anon_sym_STAR,
    ACTIONS(138), 1,
      anon_sym_LPAREN,
    ACTIONS(180), 1,
      anon_sym_PLUS,
    ACTIONS(276), 1,
      anon_sym_RPAREN,
    STATE(25), 1,
      sym_arguments,
  [1452] = 3,
    ACTIONS(278), 1,
      anon_sym_RPAREN,
    ACTIONS(280), 1,
      sym_identifier,
    STATE(75), 2,
      aux_sym__parameter_list,
      sym__parameter,
  [1463] = 3,
    ACTIONS(283), 1,
      anon_sym_RPAREN,
    ACTIONS(285), 1,
      sym_identifier,
    STATE(75), 2,
      aux_sym__parameter_list,
      sym__parameter,
  [1474] = 3,
    ACTIONS(285), 1,
      sym_identifier,
    ACTIONS(287), 1,
      anon_sym_RPAREN,
    STATE(76), 2,
      aux_sym__parameter_list,
      sym__parameter,
  [1485] = 2,
    ACTIONS(291), 1,
      anon_sym_COMMA,
    ACTIONS(289), 2,
      anon_sym_RPAREN,
      sym_identifier,
  [1493] = 2,
    ACTIONS(293), 1,
      anon_sym_LBRACE,
    STATE(66), 1,
      sym_block,
  [1500] = 1,
    ACTIONS(295), 2,
      anon_sym_RPAREN,
      sym_identifier,
  [1505] = 2,
    ACTIONS(297), 1,
      anon_sym_LBRACE,
    STATE(61), 1,
      sym_block,
  [1512] = 2,
    ACTIONS(299), 1,
      anon_sym_LBRACE,
    STATE(27), 1,
      sym_block,
  [1519] = 2,
    ACTIONS(301), 1,
      anon_sym_LPAREN,
    STATE(79), 1,
      sym_parameters,
  [1526] = 2,
    ACTIONS(301), 1,
      anon_sym_LPAREN,
    STATE(82), 1,
      sym_parameters,
  [1533] = 2,
    ACTIONS(301), 1,
      anon_sym_LPAREN,
    STATE(81), 1,
      sym_parameters,
  [1540] = 1,
    ACTIONS(303), 1,
      sym_identifier,
  [1544] = 1,
    ACTIONS(305), 1,
      anon_sym_LBRACE,
  [1548] = 1,
    ACTIONS(307), 1,
      anon_sym_EQ,
  [1552] = 1,
    ACTIONS(309), 1,
      anon_sym_LBRACE,
  [1556] = 1,
    ACTIONS(311), 1,
      anon_sym_EQ,
  [1560] = 1,
    ACTIONS(313), 1,
      sym_identifier,
  [1564] = 1,
    ACTIONS(315), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(11)] = 0,
  [SMALL_STATE(12)] = 33,
  [SMALL_STATE(13)] = 66,
  [SMALL_STATE(14)] = 99,
  [SMALL_STATE(15)] = 132,
  [SMALL_STATE(16)] = 165,
  [SMALL_STATE(17)] = 198,
  [SMALL_STATE(18)] = 231,
  [SMALL_STATE(19)] = 256,
  [SMALL_STATE(20)] = 279,
  [SMALL_STATE(21)] = 302,
  [SMALL_STATE(22)] = 328,
  [SMALL_STATE(23)] = 354,
  [SMALL_STATE(24)] = 380,
  [SMALL_STATE(25)] = 406,
  [SMALL_STATE(26)] = 424,
  [SMALL_STATE(27)] = 450,
  [SMALL_STATE(28)] = 468,
  [SMALL_STATE(29)] = 494,
  [SMALL_STATE(30)] = 520,
  [SMALL_STATE(31)] = 538,
  [SMALL_STATE(32)] = 564,
  [SMALL_STATE(33)] = 590,
  [SMALL_STATE(34)] = 616,
  [SMALL_STATE(35)] = 642,
  [SMALL_STATE(36)] = 668,
  [SMALL_STATE(37)] = 686,
  [SMALL_STATE(38)] = 704,
  [SMALL_STATE(39)] = 730,
  [SMALL_STATE(40)] = 754,
  [SMALL_STATE(41)] = 772,
  [SMALL_STATE(42)] = 798,
  [SMALL_STATE(43)] = 816,
  [SMALL_STATE(44)] = 842,
  [SMALL_STATE(45)] = 868,
  [SMALL_STATE(46)] = 894,
  [SMALL_STATE(47)] = 916,
  [SMALL_STATE(48)] = 942,
  [SMALL_STATE(49)] = 968,
  [SMALL_STATE(50)] = 994,
  [SMALL_STATE(51)] = 1020,
  [SMALL_STATE(52)] = 1042,
  [SMALL_STATE(53)] = 1068,
  [SMALL_STATE(54)] = 1085,
  [SMALL_STATE(55)] = 1102,
  [SMALL_STATE(56)] = 1129,
  [SMALL_STATE(57)] = 1152,
  [SMALL_STATE(58)] = 1169,
  [SMALL_STATE(59)] = 1186,
  [SMALL_STATE(60)] = 1203,
  [SMALL_STATE(61)] = 1224,
  [SMALL_STATE(62)] = 1241,
  [SMALL_STATE(63)] = 1262,
  [SMALL_STATE(64)] = 1279,
  [SMALL_STATE(65)] = 1295,
  [SMALL_STATE(66)] = 1311,
  [SMALL_STATE(67)] = 1327,
  [SMALL_STATE(68)] = 1343,
  [SMALL_STATE(69)] = 1359,
  [SMALL_STATE(70)] = 1375,
  [SMALL_STATE(71)] = 1391,
  [SMALL_STATE(72)] = 1404,
  [SMALL_STATE(73)] = 1420,
  [SMALL_STATE(74)] = 1436,
  [SMALL_STATE(75)] = 1452,
  [SMALL_STATE(76)] = 1463,
  [SMALL_STATE(77)] = 1474,
  [SMALL_STATE(78)] = 1485,
  [SMALL_STATE(79)] = 1493,
  [SMALL_STATE(80)] = 1500,
  [SMALL_STATE(81)] = 1505,
  [SMALL_STATE(82)] = 1512,
  [SMALL_STATE(83)] = 1519,
  [SMALL_STATE(84)] = 1526,
  [SMALL_STATE(85)] = 1533,
  [SMALL_STATE(86)] = 1540,
  [SMALL_STATE(87)] = 1544,
  [SMALL_STATE(88)] = 1548,
  [SMALL_STATE(89)] = 1552,
  [SMALL_STATE(90)] = 1556,
  [SMALL_STATE(91)] = 1560,
  [SMALL_STATE(92)] = 1564,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statement_list, 2), SHIFT_REPEAT(91),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__statement_list, 2), SHIFT_REPEAT(23),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statement_list, 2), SHIFT_REPEAT(85),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__statement_list, 2),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statement_list, 2), SHIFT_REPEAT(35),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__statement_list, 2), SHIFT_REPEAT(21),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__statement_list, 2), SHIFT_REPEAT(44),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statement_list, 2), SHIFT_REPEAT(44),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(86),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(43),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(84),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(38),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(22),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(32),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(32),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__argument_list, 2), SHIFT_REPEAT(41),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__argument_list, 2),
  [112] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__argument_list, 2), SHIFT_REPEAT(83),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__argument_list, 2), SHIFT_REPEAT(34),
  [118] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__argument_list, 2), SHIFT_REPEAT(55),
  [121] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__argument_list, 2), SHIFT_REPEAT(55),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [146] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [154] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [158] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 2),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 2),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 3),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 3),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 2),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 2),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 2),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arguments, 2),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [188] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 1),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 1),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_statement, 4),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_statement, 4),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [200] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [204] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__grouped_expression, 3),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__grouped_expression, 3),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [216] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 3),
  [224] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arguments, 3),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [228] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [232] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [236] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [242] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [246] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [250] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [254] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__argument, 1),
  [264] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__argument, 1),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__argument, 2),
  [270] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__argument, 2),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__parameter_list, 2),
  [280] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__parameter_list, 2), SHIFT_REPEAT(78),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [289] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parameter, 1),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parameter, 2),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 2),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [309] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 3),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [315] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_monkeylang(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
