#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 98
#define LARGE_STATE_COUNT 12
#define SYMBOL_COUNT 52
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 2

enum ts_symbol_identifiers {
  anon_sym_let = 1,
  anon_sym_EQ = 2,
  anon_sym_SEMI = 3,
  anon_sym_STAR = 4,
  anon_sym_PLUS = 5,
  anon_sym_LPAREN = 6,
  anon_sym_RPAREN = 7,
  anon_sym_fn = 8,
  anon_sym_COMMA = 9,
  anon_sym_return = 10,
  anon_sym_LBRACE = 11,
  anon_sym_RBRACE = 12,
  anon_sym_DOT = 13,
  anon_sym_LBRACK = 14,
  anon_sym_RBRACK = 15,
  anon_sym_COLON = 16,
  anon_sym_DQUOTE = 17,
  anon_sym_DASH = 18,
  anon_sym_BANG = 19,
  sym_number = 20,
  sym_boolean = 21,
  sym__string = 22,
  sym_identifier = 23,
  sym_source_file = 24,
  sym__statement = 25,
  sym_let_statement = 26,
  sym__expression_statement = 27,
  sym__expression = 28,
  sym_binary_expression = 29,
  sym__grouped_expression = 30,
  sym_function = 31,
  sym_parameters = 32,
  aux_sym__parameter_list = 33,
  sym_parameter = 34,
  sym_body = 35,
  sym_return_statement = 36,
  sym__block_statement = 37,
  aux_sym__statement_list = 38,
  sym_function_call = 39,
  sym_method_call = 40,
  sym_arguments = 41,
  aux_sym__argument_list = 42,
  sym__argument = 43,
  sym_array_literal = 44,
  sym_hash_literal = 45,
  aux_sym__kv_pairs = 46,
  sym_kv_pair = 47,
  sym_index_expression = 48,
  sym_string_literal = 49,
  sym_unary_expression = 50,
  aux_sym_source_file_repeat1 = 51,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [anon_sym_STAR] = "*",
  [anon_sym_PLUS] = "+",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_fn] = "fn",
  [anon_sym_COMMA] = ",",
  [anon_sym_return] = "return",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_DOT] = ".",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COLON] = ":",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_DASH] = "-",
  [anon_sym_BANG] = "!",
  [sym_number] = "number",
  [sym_boolean] = "boolean",
  [sym__string] = "_string",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_let_statement] = "let_statement",
  [sym__expression_statement] = "_expression_statement",
  [sym__expression] = "_expression",
  [sym_binary_expression] = "binary_expression",
  [sym__grouped_expression] = "_grouped_expression",
  [sym_function] = "function",
  [sym_parameters] = "parameters",
  [aux_sym__parameter_list] = "_parameter_list",
  [sym_parameter] = "parameter",
  [sym_body] = "body",
  [sym_return_statement] = "return_statement",
  [sym__block_statement] = "_block_statement",
  [aux_sym__statement_list] = "_statement_list",
  [sym_function_call] = "function_call",
  [sym_method_call] = "method_call",
  [sym_arguments] = "arguments",
  [aux_sym__argument_list] = "_argument_list",
  [sym__argument] = "_argument",
  [sym_array_literal] = "array_literal",
  [sym_hash_literal] = "hash_literal",
  [aux_sym__kv_pairs] = "_kv_pairs",
  [sym_kv_pair] = "kv_pair",
  [sym_index_expression] = "index_expression",
  [sym_string_literal] = "string_literal",
  [sym_unary_expression] = "unary_expression",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_BANG] = anon_sym_BANG,
  [sym_number] = sym_number,
  [sym_boolean] = sym_boolean,
  [sym__string] = sym__string,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_let_statement] = sym_let_statement,
  [sym__expression_statement] = sym__expression_statement,
  [sym__expression] = sym__expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym__grouped_expression] = sym__grouped_expression,
  [sym_function] = sym_function,
  [sym_parameters] = sym_parameters,
  [aux_sym__parameter_list] = aux_sym__parameter_list,
  [sym_parameter] = sym_parameter,
  [sym_body] = sym_body,
  [sym_return_statement] = sym_return_statement,
  [sym__block_statement] = sym__block_statement,
  [aux_sym__statement_list] = aux_sym__statement_list,
  [sym_function_call] = sym_function_call,
  [sym_method_call] = sym_method_call,
  [sym_arguments] = sym_arguments,
  [aux_sym__argument_list] = aux_sym__argument_list,
  [sym__argument] = sym__argument,
  [sym_array_literal] = sym_array_literal,
  [sym_hash_literal] = sym_hash_literal,
  [aux_sym__kv_pairs] = aux_sym__kv_pairs,
  [sym_kv_pair] = sym_kv_pair,
  [sym_index_expression] = sym_index_expression,
  [sym_string_literal] = sym_string_literal,
  [sym_unary_expression] = sym_unary_expression,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym__string] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_let_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression_statement] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__grouped_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_parameters] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__parameter_list] = {
    .visible = false,
    .named = false,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__block_statement] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__statement_list] = {
    .visible = false,
    .named = false,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_method_call] = {
    .visible = true,
    .named = true,
  },
  [sym_arguments] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__argument_list] = {
    .visible = false,
    .named = false,
  },
  [sym__argument] = {
    .visible = false,
    .named = true,
  },
  [sym_array_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_hash_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__kv_pairs] = {
    .visible = false,
    .named = false,
  },
  [sym_kv_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_index_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_left = 1,
  field_right = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_left] = "left",
  [field_right] = "right",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_left, 1},
    {field_right, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 8,
  [10] = 8,
  [11] = 6,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 23,
  [28] = 28,
  [29] = 28,
  [30] = 22,
  [31] = 24,
  [32] = 21,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 52,
  [54] = 34,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 59,
  [61] = 34,
  [62] = 62,
  [63] = 62,
  [64] = 58,
  [65] = 65,
  [66] = 66,
  [67] = 55,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 71,
  [76] = 73,
  [77] = 69,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 82,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 85,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 92,
  [97] = 94,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      if (lookahead == '!') ADVANCE(24);
      if (lookahead == '"') ADVANCE(22);
      if (lookahead == '(') ADVANCE(11);
      if (lookahead == ')') ADVANCE(12);
      if (lookahead == '*') ADVANCE(9);
      if (lookahead == '+') ADVANCE(10);
      if (lookahead == ',') ADVANCE(14);
      if (lookahead == '-') ADVANCE(23);
      if (lookahead == '.') ADVANCE(18);
      if (lookahead == ':') ADVANCE(21);
      if (lookahead == ';') ADVANCE(8);
      if (lookahead == '=') ADVANCE(7);
      if (lookahead == '[') ADVANCE(19);
      if (lookahead == ']') ADVANCE(20);
      if (lookahead == 'f') ADVANCE(28);
      if (lookahead == 'l') ADVANCE(29);
      if (lookahead == 'r') ADVANCE(31);
      if (lookahead == 't') ADVANCE(35);
      if (lookahead == '{') ADVANCE(16);
      if (lookahead == '}') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(24);
      if (lookahead == '"') ADVANCE(22);
      if (lookahead == '(') ADVANCE(11);
      if (lookahead == ')') ADVANCE(12);
      if (lookahead == '*') ADVANCE(9);
      if (lookahead == '+') ADVANCE(10);
      if (lookahead == ',') ADVANCE(14);
      if (lookahead == '-') ADVANCE(23);
      if (lookahead == '.') ADVANCE(18);
      if (lookahead == ':') ADVANCE(21);
      if (lookahead == ';') ADVANCE(8);
      if (lookahead == '[') ADVANCE(19);
      if (lookahead == ']') ADVANCE(20);
      if (lookahead == 'f') ADVANCE(28);
      if (lookahead == 't') ADVANCE(35);
      if (lookahead == '{') ADVANCE(16);
      if (lookahead == '}') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2)
      if (lookahead != 0 &&
          lookahead != '^') ADVANCE(27);
      END_STATE();
    case 3:
      if (lookahead == ')') ADVANCE(12);
      if (lookahead == ',') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 4:
      if (lookahead == 'f') ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_let);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_fn);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_return);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_boolean);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym__string);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '^') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(32);
      if (lookahead == 'n') ADVANCE(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(38);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(39);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(34);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(30);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(6);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(30);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 3},
  [79] = {.lex_state = 4},
  [80] = {.lex_state = 3},
  [81] = {.lex_state = 3},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 3},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 2},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 3},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 3},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 3},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_boolean] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(95),
    [sym__statement] = STATE(5),
    [sym_let_statement] = STATE(5),
    [sym__expression_statement] = STATE(5),
    [sym__expression] = STATE(73),
    [sym_binary_expression] = STATE(73),
    [sym__grouped_expression] = STATE(73),
    [sym_function] = STATE(33),
    [sym_return_statement] = STATE(5),
    [sym__block_statement] = STATE(5),
    [sym_function_call] = STATE(73),
    [sym_method_call] = STATE(73),
    [sym_array_literal] = STATE(73),
    [sym_hash_literal] = STATE(73),
    [sym_index_expression] = STATE(73),
    [sym_string_literal] = STATE(73),
    [sym_unary_expression] = STATE(73),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_let] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(19),
    [anon_sym_BANG] = ACTIONS(19),
    [sym_number] = ACTIONS(21),
    [sym_boolean] = ACTIONS(23),
    [sym_identifier] = ACTIONS(25),
  },
  [2] = {
    [sym__statement] = STATE(8),
    [sym_let_statement] = STATE(8),
    [sym__expression_statement] = STATE(8),
    [sym__expression] = STATE(68),
    [sym_binary_expression] = STATE(68),
    [sym__grouped_expression] = STATE(68),
    [sym_function] = STATE(33),
    [sym_return_statement] = STATE(8),
    [sym__block_statement] = STATE(8),
    [aux_sym__statement_list] = STATE(8),
    [sym_function_call] = STATE(68),
    [sym_method_call] = STATE(68),
    [sym_array_literal] = STATE(68),
    [sym_hash_literal] = STATE(68),
    [aux_sym__kv_pairs] = STATE(14),
    [sym_kv_pair] = STATE(14),
    [sym_index_expression] = STATE(68),
    [sym_string_literal] = STATE(68),
    [sym_unary_expression] = STATE(68),
    [anon_sym_let] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(29),
    [anon_sym_LBRACE] = ACTIONS(31),
    [anon_sym_RBRACE] = ACTIONS(33),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(19),
    [anon_sym_BANG] = ACTIONS(19),
    [sym_number] = ACTIONS(35),
    [sym_boolean] = ACTIONS(37),
    [sym_identifier] = ACTIONS(25),
  },
  [3] = {
    [sym__statement] = STATE(10),
    [sym_let_statement] = STATE(10),
    [sym__expression_statement] = STATE(10),
    [sym__expression] = STATE(68),
    [sym_binary_expression] = STATE(68),
    [sym__grouped_expression] = STATE(68),
    [sym_function] = STATE(33),
    [sym_return_statement] = STATE(10),
    [sym__block_statement] = STATE(10),
    [aux_sym__statement_list] = STATE(10),
    [sym_function_call] = STATE(68),
    [sym_method_call] = STATE(68),
    [sym_array_literal] = STATE(68),
    [sym_hash_literal] = STATE(68),
    [aux_sym__kv_pairs] = STATE(14),
    [sym_kv_pair] = STATE(14),
    [sym_index_expression] = STATE(68),
    [sym_string_literal] = STATE(68),
    [sym_unary_expression] = STATE(68),
    [anon_sym_let] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(29),
    [anon_sym_LBRACE] = ACTIONS(31),
    [anon_sym_RBRACE] = ACTIONS(39),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(19),
    [anon_sym_BANG] = ACTIONS(19),
    [sym_number] = ACTIONS(35),
    [sym_boolean] = ACTIONS(37),
    [sym_identifier] = ACTIONS(25),
  },
  [4] = {
    [sym__statement] = STATE(4),
    [sym_let_statement] = STATE(4),
    [sym__expression_statement] = STATE(4),
    [sym__expression] = STATE(76),
    [sym_binary_expression] = STATE(76),
    [sym__grouped_expression] = STATE(76),
    [sym_function] = STATE(33),
    [sym_return_statement] = STATE(4),
    [sym__block_statement] = STATE(4),
    [aux_sym__statement_list] = STATE(4),
    [sym_function_call] = STATE(76),
    [sym_method_call] = STATE(76),
    [sym_array_literal] = STATE(76),
    [sym_hash_literal] = STATE(76),
    [sym_index_expression] = STATE(76),
    [sym_string_literal] = STATE(76),
    [sym_unary_expression] = STATE(76),
    [anon_sym_let] = ACTIONS(41),
    [anon_sym_LPAREN] = ACTIONS(44),
    [anon_sym_fn] = ACTIONS(47),
    [anon_sym_return] = ACTIONS(50),
    [anon_sym_LBRACE] = ACTIONS(53),
    [anon_sym_RBRACE] = ACTIONS(56),
    [anon_sym_LBRACK] = ACTIONS(58),
    [anon_sym_DQUOTE] = ACTIONS(61),
    [anon_sym_DASH] = ACTIONS(64),
    [anon_sym_BANG] = ACTIONS(64),
    [sym_number] = ACTIONS(67),
    [sym_boolean] = ACTIONS(70),
    [sym_identifier] = ACTIONS(73),
  },
  [5] = {
    [sym__statement] = STATE(7),
    [sym_let_statement] = STATE(7),
    [sym__expression_statement] = STATE(7),
    [sym__expression] = STATE(73),
    [sym_binary_expression] = STATE(73),
    [sym__grouped_expression] = STATE(73),
    [sym_function] = STATE(33),
    [sym_return_statement] = STATE(7),
    [sym__block_statement] = STATE(7),
    [sym_function_call] = STATE(73),
    [sym_method_call] = STATE(73),
    [sym_array_literal] = STATE(73),
    [sym_hash_literal] = STATE(73),
    [sym_index_expression] = STATE(73),
    [sym_string_literal] = STATE(73),
    [sym_unary_expression] = STATE(73),
    [aux_sym_source_file_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(76),
    [anon_sym_let] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(19),
    [anon_sym_BANG] = ACTIONS(19),
    [sym_number] = ACTIONS(21),
    [sym_boolean] = ACTIONS(23),
    [sym_identifier] = ACTIONS(25),
  },
  [6] = {
    [sym__statement] = STATE(8),
    [sym_let_statement] = STATE(8),
    [sym__expression_statement] = STATE(8),
    [sym__expression] = STATE(76),
    [sym_binary_expression] = STATE(76),
    [sym__grouped_expression] = STATE(76),
    [sym_function] = STATE(33),
    [sym_return_statement] = STATE(8),
    [sym__block_statement] = STATE(8),
    [aux_sym__statement_list] = STATE(8),
    [sym_function_call] = STATE(76),
    [sym_method_call] = STATE(76),
    [sym_array_literal] = STATE(76),
    [sym_hash_literal] = STATE(76),
    [sym_index_expression] = STATE(76),
    [sym_string_literal] = STATE(76),
    [sym_unary_expression] = STATE(76),
    [anon_sym_let] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(29),
    [anon_sym_LBRACE] = ACTIONS(31),
    [anon_sym_RBRACE] = ACTIONS(78),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(19),
    [anon_sym_BANG] = ACTIONS(19),
    [sym_number] = ACTIONS(80),
    [sym_boolean] = ACTIONS(82),
    [sym_identifier] = ACTIONS(25),
  },
  [7] = {
    [sym__statement] = STATE(7),
    [sym_let_statement] = STATE(7),
    [sym__expression_statement] = STATE(7),
    [sym__expression] = STATE(73),
    [sym_binary_expression] = STATE(73),
    [sym__grouped_expression] = STATE(73),
    [sym_function] = STATE(33),
    [sym_return_statement] = STATE(7),
    [sym__block_statement] = STATE(7),
    [sym_function_call] = STATE(73),
    [sym_method_call] = STATE(73),
    [sym_array_literal] = STATE(73),
    [sym_hash_literal] = STATE(73),
    [sym_index_expression] = STATE(73),
    [sym_string_literal] = STATE(73),
    [sym_unary_expression] = STATE(73),
    [aux_sym_source_file_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(84),
    [anon_sym_let] = ACTIONS(86),
    [anon_sym_LPAREN] = ACTIONS(89),
    [anon_sym_fn] = ACTIONS(92),
    [anon_sym_return] = ACTIONS(95),
    [anon_sym_LBRACE] = ACTIONS(98),
    [anon_sym_LBRACK] = ACTIONS(101),
    [anon_sym_DQUOTE] = ACTIONS(104),
    [anon_sym_DASH] = ACTIONS(107),
    [anon_sym_BANG] = ACTIONS(107),
    [sym_number] = ACTIONS(110),
    [sym_boolean] = ACTIONS(113),
    [sym_identifier] = ACTIONS(116),
  },
  [8] = {
    [sym__statement] = STATE(4),
    [sym_let_statement] = STATE(4),
    [sym__expression_statement] = STATE(4),
    [sym__expression] = STATE(76),
    [sym_binary_expression] = STATE(76),
    [sym__grouped_expression] = STATE(76),
    [sym_function] = STATE(33),
    [sym_return_statement] = STATE(4),
    [sym__block_statement] = STATE(4),
    [aux_sym__statement_list] = STATE(4),
    [sym_function_call] = STATE(76),
    [sym_method_call] = STATE(76),
    [sym_array_literal] = STATE(76),
    [sym_hash_literal] = STATE(76),
    [sym_index_expression] = STATE(76),
    [sym_string_literal] = STATE(76),
    [sym_unary_expression] = STATE(76),
    [anon_sym_let] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(29),
    [anon_sym_LBRACE] = ACTIONS(31),
    [anon_sym_RBRACE] = ACTIONS(119),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(19),
    [anon_sym_BANG] = ACTIONS(19),
    [sym_number] = ACTIONS(80),
    [sym_boolean] = ACTIONS(82),
    [sym_identifier] = ACTIONS(25),
  },
  [9] = {
    [sym__statement] = STATE(4),
    [sym_let_statement] = STATE(4),
    [sym__expression_statement] = STATE(4),
    [sym__expression] = STATE(76),
    [sym_binary_expression] = STATE(76),
    [sym__grouped_expression] = STATE(76),
    [sym_function] = STATE(33),
    [sym_return_statement] = STATE(4),
    [sym__block_statement] = STATE(4),
    [aux_sym__statement_list] = STATE(4),
    [sym_function_call] = STATE(76),
    [sym_method_call] = STATE(76),
    [sym_array_literal] = STATE(76),
    [sym_hash_literal] = STATE(76),
    [sym_index_expression] = STATE(76),
    [sym_string_literal] = STATE(76),
    [sym_unary_expression] = STATE(76),
    [anon_sym_let] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(29),
    [anon_sym_LBRACE] = ACTIONS(31),
    [anon_sym_RBRACE] = ACTIONS(121),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(19),
    [anon_sym_BANG] = ACTIONS(19),
    [sym_number] = ACTIONS(80),
    [sym_boolean] = ACTIONS(82),
    [sym_identifier] = ACTIONS(25),
  },
  [10] = {
    [sym__statement] = STATE(4),
    [sym_let_statement] = STATE(4),
    [sym__expression_statement] = STATE(4),
    [sym__expression] = STATE(76),
    [sym_binary_expression] = STATE(76),
    [sym__grouped_expression] = STATE(76),
    [sym_function] = STATE(33),
    [sym_return_statement] = STATE(4),
    [sym__block_statement] = STATE(4),
    [aux_sym__statement_list] = STATE(4),
    [sym_function_call] = STATE(76),
    [sym_method_call] = STATE(76),
    [sym_array_literal] = STATE(76),
    [sym_hash_literal] = STATE(76),
    [sym_index_expression] = STATE(76),
    [sym_string_literal] = STATE(76),
    [sym_unary_expression] = STATE(76),
    [anon_sym_let] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(29),
    [anon_sym_LBRACE] = ACTIONS(31),
    [anon_sym_RBRACE] = ACTIONS(123),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(19),
    [anon_sym_BANG] = ACTIONS(19),
    [sym_number] = ACTIONS(80),
    [sym_boolean] = ACTIONS(82),
    [sym_identifier] = ACTIONS(25),
  },
  [11] = {
    [sym__statement] = STATE(9),
    [sym_let_statement] = STATE(9),
    [sym__expression_statement] = STATE(9),
    [sym__expression] = STATE(76),
    [sym_binary_expression] = STATE(76),
    [sym__grouped_expression] = STATE(76),
    [sym_function] = STATE(33),
    [sym_return_statement] = STATE(9),
    [sym__block_statement] = STATE(9),
    [aux_sym__statement_list] = STATE(9),
    [sym_function_call] = STATE(76),
    [sym_method_call] = STATE(76),
    [sym_array_literal] = STATE(76),
    [sym_hash_literal] = STATE(76),
    [sym_index_expression] = STATE(76),
    [sym_string_literal] = STATE(76),
    [sym_unary_expression] = STATE(76),
    [anon_sym_let] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(29),
    [anon_sym_LBRACE] = ACTIONS(31),
    [anon_sym_RBRACE] = ACTIONS(78),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(19),
    [anon_sym_BANG] = ACTIONS(19),
    [sym_number] = ACTIONS(80),
    [sym_boolean] = ACTIONS(82),
    [sym_identifier] = ACTIONS(25),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(125), 1,
      anon_sym_LPAREN,
    ACTIONS(130), 1,
      anon_sym_fn,
    ACTIONS(133), 1,
      anon_sym_LBRACE,
    ACTIONS(136), 1,
      anon_sym_LBRACK,
    ACTIONS(139), 1,
      anon_sym_DQUOTE,
    ACTIONS(145), 1,
      sym_number,
    ACTIONS(148), 1,
      sym_boolean,
    ACTIONS(151), 1,
      sym_identifier,
    STATE(33), 1,
      sym_function,
    ACTIONS(128), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
    ACTIONS(142), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(12), 2,
      aux_sym__argument_list,
      sym__argument,
    STATE(56), 10,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function_call,
      sym_method_call,
      sym_array_literal,
      sym_hash_literal,
      sym_index_expression,
      sym_string_literal,
      sym_unary_expression,
  [52] = 13,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(154), 1,
      anon_sym_fn,
    ACTIONS(156), 1,
      anon_sym_LBRACE,
    ACTIONS(158), 1,
      anon_sym_RBRACK,
    ACTIONS(162), 1,
      sym_number,
    ACTIONS(164), 1,
      sym_boolean,
    STATE(33), 1,
      sym_function,
    ACTIONS(160), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(12), 2,
      aux_sym__argument_list,
      sym__argument,
    STATE(56), 10,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function_call,
      sym_method_call,
      sym_array_literal,
      sym_hash_literal,
      sym_index_expression,
      sym_string_literal,
      sym_unary_expression,
  [103] = 13,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(156), 1,
      anon_sym_LBRACE,
    ACTIONS(166), 1,
      anon_sym_RBRACE,
    ACTIONS(168), 1,
      sym_number,
    ACTIONS(170), 1,
      sym_boolean,
    STATE(33), 1,
      sym_function,
    ACTIONS(19), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(18), 2,
      aux_sym__kv_pairs,
      sym_kv_pair,
    STATE(70), 10,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function_call,
      sym_method_call,
      sym_array_literal,
      sym_hash_literal,
      sym_index_expression,
      sym_string_literal,
      sym_unary_expression,
  [154] = 13,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(154), 1,
      anon_sym_fn,
    ACTIONS(156), 1,
      anon_sym_LBRACE,
    ACTIONS(162), 1,
      sym_number,
    ACTIONS(164), 1,
      sym_boolean,
    ACTIONS(172), 1,
      anon_sym_RBRACK,
    STATE(33), 1,
      sym_function,
    ACTIONS(160), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(13), 2,
      aux_sym__argument_list,
      sym__argument,
    STATE(56), 10,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function_call,
      sym_method_call,
      sym_array_literal,
      sym_hash_literal,
      sym_index_expression,
      sym_string_literal,
      sym_unary_expression,
  [205] = 13,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(154), 1,
      anon_sym_fn,
    ACTIONS(156), 1,
      anon_sym_LBRACE,
    ACTIONS(162), 1,
      sym_number,
    ACTIONS(164), 1,
      sym_boolean,
    ACTIONS(174), 1,
      anon_sym_RPAREN,
    STATE(33), 1,
      sym_function,
    ACTIONS(160), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(19), 2,
      aux_sym__argument_list,
      sym__argument,
    STATE(56), 10,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function_call,
      sym_method_call,
      sym_array_literal,
      sym_hash_literal,
      sym_index_expression,
      sym_string_literal,
      sym_unary_expression,
  [256] = 13,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(156), 1,
      anon_sym_LBRACE,
    ACTIONS(168), 1,
      sym_number,
    ACTIONS(170), 1,
      sym_boolean,
    ACTIONS(176), 1,
      anon_sym_RBRACE,
    STATE(33), 1,
      sym_function,
    ACTIONS(19), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(14), 2,
      aux_sym__kv_pairs,
      sym_kv_pair,
    STATE(70), 10,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function_call,
      sym_method_call,
      sym_array_literal,
      sym_hash_literal,
      sym_index_expression,
      sym_string_literal,
      sym_unary_expression,
  [307] = 13,
    ACTIONS(178), 1,
      anon_sym_LPAREN,
    ACTIONS(181), 1,
      anon_sym_fn,
    ACTIONS(184), 1,
      anon_sym_LBRACE,
    ACTIONS(187), 1,
      anon_sym_RBRACE,
    ACTIONS(189), 1,
      anon_sym_LBRACK,
    ACTIONS(192), 1,
      anon_sym_DQUOTE,
    ACTIONS(198), 1,
      sym_number,
    ACTIONS(201), 1,
      sym_boolean,
    ACTIONS(204), 1,
      sym_identifier,
    STATE(33), 1,
      sym_function,
    ACTIONS(195), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(18), 2,
      aux_sym__kv_pairs,
      sym_kv_pair,
    STATE(70), 10,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function_call,
      sym_method_call,
      sym_array_literal,
      sym_hash_literal,
      sym_index_expression,
      sym_string_literal,
      sym_unary_expression,
  [358] = 13,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(154), 1,
      anon_sym_fn,
    ACTIONS(156), 1,
      anon_sym_LBRACE,
    ACTIONS(162), 1,
      sym_number,
    ACTIONS(164), 1,
      sym_boolean,
    ACTIONS(207), 1,
      anon_sym_RPAREN,
    STATE(33), 1,
      sym_function,
    ACTIONS(160), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(12), 2,
      aux_sym__argument_list,
      sym__argument,
    STATE(56), 10,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function_call,
      sym_method_call,
      sym_array_literal,
      sym_hash_literal,
      sym_index_expression,
      sym_string_literal,
      sym_unary_expression,
  [409] = 11,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(156), 1,
      anon_sym_LBRACE,
    ACTIONS(209), 1,
      sym_number,
    ACTIONS(211), 1,
      sym_boolean,
    STATE(33), 1,
      sym_function,
    ACTIONS(19), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(74), 10,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function_call,
      sym_method_call,
      sym_array_literal,
      sym_hash_literal,
      sym_index_expression,
      sym_string_literal,
      sym_unary_expression,
  [453] = 11,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(154), 1,
      anon_sym_fn,
    ACTIONS(156), 1,
      anon_sym_LBRACE,
    ACTIONS(213), 1,
      sym_number,
    ACTIONS(215), 1,
      sym_boolean,
    STATE(33), 1,
      sym_function,
    ACTIONS(160), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(55), 10,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function_call,
      sym_method_call,
      sym_array_literal,
      sym_hash_literal,
      sym_index_expression,
      sym_string_literal,
      sym_unary_expression,
  [497] = 11,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(156), 1,
      anon_sym_LBRACE,
    ACTIONS(217), 1,
      sym_number,
    ACTIONS(219), 1,
      sym_boolean,
    STATE(33), 1,
      sym_function,
    ACTIONS(19), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(69), 10,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function_call,
      sym_method_call,
      sym_array_literal,
      sym_hash_literal,
      sym_index_expression,
      sym_string_literal,
      sym_unary_expression,
  [541] = 11,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(156), 1,
      anon_sym_LBRACE,
    ACTIONS(221), 1,
      sym_number,
    ACTIONS(223), 1,
      sym_boolean,
    STATE(33), 1,
      sym_function,
    ACTIONS(19), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(37), 10,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function_call,
      sym_method_call,
      sym_array_literal,
      sym_hash_literal,
      sym_index_expression,
      sym_string_literal,
      sym_unary_expression,
  [585] = 11,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(154), 1,
      anon_sym_fn,
    ACTIONS(156), 1,
      anon_sym_LBRACE,
    ACTIONS(225), 1,
      sym_number,
    ACTIONS(227), 1,
      sym_boolean,
    STATE(33), 1,
      sym_function,
    ACTIONS(160), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(36), 10,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function_call,
      sym_method_call,
      sym_array_literal,
      sym_hash_literal,
      sym_index_expression,
      sym_string_literal,
      sym_unary_expression,
  [629] = 11,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(154), 1,
      anon_sym_fn,
    ACTIONS(156), 1,
      anon_sym_LBRACE,
    ACTIONS(229), 1,
      sym_number,
    ACTIONS(231), 1,
      sym_boolean,
    STATE(33), 1,
      sym_function,
    ACTIONS(160), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(57), 10,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function_call,
      sym_method_call,
      sym_array_literal,
      sym_hash_literal,
      sym_index_expression,
      sym_string_literal,
      sym_unary_expression,
  [673] = 11,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(156), 1,
      anon_sym_LBRACE,
    ACTIONS(233), 1,
      sym_number,
    ACTIONS(235), 1,
      sym_boolean,
    STATE(33), 1,
      sym_function,
    ACTIONS(19), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(72), 10,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function_call,
      sym_method_call,
      sym_array_literal,
      sym_hash_literal,
      sym_index_expression,
      sym_string_literal,
      sym_unary_expression,
  [717] = 11,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(154), 1,
      anon_sym_fn,
    ACTIONS(156), 1,
      anon_sym_LBRACE,
    ACTIONS(221), 1,
      sym_number,
    ACTIONS(223), 1,
      sym_boolean,
    STATE(33), 1,
      sym_function,
    ACTIONS(160), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(37), 10,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function_call,
      sym_method_call,
      sym_array_literal,
      sym_hash_literal,
      sym_index_expression,
      sym_string_literal,
      sym_unary_expression,
  [761] = 11,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(156), 1,
      anon_sym_LBRACE,
    ACTIONS(237), 1,
      sym_number,
    ACTIONS(239), 1,
      sym_boolean,
    STATE(33), 1,
      sym_function,
    ACTIONS(19), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(75), 10,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function_call,
      sym_method_call,
      sym_array_literal,
      sym_hash_literal,
      sym_index_expression,
      sym_string_literal,
      sym_unary_expression,
  [805] = 11,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(156), 1,
      anon_sym_LBRACE,
    ACTIONS(241), 1,
      sym_number,
    ACTIONS(243), 1,
      sym_boolean,
    STATE(33), 1,
      sym_function,
    ACTIONS(19), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(71), 10,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function_call,
      sym_method_call,
      sym_array_literal,
      sym_hash_literal,
      sym_index_expression,
      sym_string_literal,
      sym_unary_expression,
  [849] = 11,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(156), 1,
      anon_sym_LBRACE,
    ACTIONS(245), 1,
      sym_number,
    ACTIONS(247), 1,
      sym_boolean,
    STATE(33), 1,
      sym_function,
    ACTIONS(19), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(77), 10,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function_call,
      sym_method_call,
      sym_array_literal,
      sym_hash_literal,
      sym_index_expression,
      sym_string_literal,
      sym_unary_expression,
  [893] = 11,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(156), 1,
      anon_sym_LBRACE,
    ACTIONS(225), 1,
      sym_number,
    ACTIONS(227), 1,
      sym_boolean,
    STATE(33), 1,
      sym_function,
    ACTIONS(19), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(36), 10,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function_call,
      sym_method_call,
      sym_array_literal,
      sym_hash_literal,
      sym_index_expression,
      sym_string_literal,
      sym_unary_expression,
  [937] = 11,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(156), 1,
      anon_sym_LBRACE,
    ACTIONS(249), 1,
      sym_number,
    ACTIONS(251), 1,
      sym_boolean,
    STATE(33), 1,
      sym_function,
    ACTIONS(19), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(67), 10,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function_call,
      sym_method_call,
      sym_array_literal,
      sym_hash_literal,
      sym_index_expression,
      sym_string_literal,
      sym_unary_expression,
  [981] = 4,
    ACTIONS(255), 1,
      anon_sym_LPAREN,
    STATE(38), 1,
      sym_arguments,
    ACTIONS(257), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(253), 15,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1010] = 2,
    ACTIONS(261), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(259), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1035] = 2,
    ACTIONS(265), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(263), 16,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1059] = 4,
    ACTIONS(271), 1,
      anon_sym_DOT,
    ACTIONS(273), 1,
      anon_sym_LBRACK,
    ACTIONS(269), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(267), 14,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1087] = 4,
    ACTIONS(271), 1,
      anon_sym_DOT,
    ACTIONS(273), 1,
      anon_sym_LBRACK,
    ACTIONS(277), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(275), 14,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1115] = 2,
    ACTIONS(281), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(279), 16,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1139] = 2,
    ACTIONS(285), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(283), 16,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1163] = 2,
    ACTIONS(289), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(287), 16,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1187] = 2,
    ACTIONS(293), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(291), 16,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1211] = 2,
    ACTIONS(297), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(295), 16,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1235] = 2,
    ACTIONS(301), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(299), 16,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1259] = 2,
    ACTIONS(305), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(303), 16,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1283] = 2,
    ACTIONS(309), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(307), 16,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1307] = 2,
    ACTIONS(313), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(311), 16,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1331] = 2,
    ACTIONS(317), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(315), 16,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1355] = 2,
    ACTIONS(321), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(319), 16,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1379] = 2,
    ACTIONS(325), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(323), 16,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1403] = 2,
    ACTIONS(329), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(327), 16,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1427] = 2,
    ACTIONS(333), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(331), 16,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1451] = 3,
    ACTIONS(285), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(291), 6,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_COLON,
    ACTIONS(283), 7,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1476] = 3,
    ACTIONS(285), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(291), 5,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_LBRACK,
    ACTIONS(283), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1500] = 2,
    ACTIONS(261), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(259), 14,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1522] = 5,
    ACTIONS(271), 1,
      anon_sym_DOT,
    ACTIONS(273), 1,
      anon_sym_LBRACK,
    ACTIONS(335), 1,
      anon_sym_STAR,
    ACTIONS(269), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(267), 11,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1550] = 7,
    ACTIONS(271), 1,
      anon_sym_DOT,
    ACTIONS(273), 1,
      anon_sym_LBRACK,
    ACTIONS(335), 1,
      anon_sym_STAR,
    ACTIONS(337), 1,
      anon_sym_PLUS,
    ACTIONS(343), 1,
      anon_sym_COMMA,
    ACTIONS(341), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(339), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1581] = 7,
    ACTIONS(271), 1,
      anon_sym_DOT,
    ACTIONS(273), 1,
      anon_sym_LBRACK,
    ACTIONS(335), 1,
      anon_sym_STAR,
    ACTIONS(337), 1,
      anon_sym_PLUS,
    ACTIONS(349), 1,
      anon_sym_COMMA,
    ACTIONS(347), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(345), 7,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1611] = 2,
    ACTIONS(351), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(353), 8,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1629] = 2,
    ACTIONS(357), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(355), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1647] = 2,
    ACTIONS(357), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(355), 8,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1665] = 2,
    ACTIONS(261), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(259), 8,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1683] = 2,
    ACTIONS(359), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(361), 8,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1701] = 2,
    ACTIONS(359), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(361), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1719] = 2,
    ACTIONS(351), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(353), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1737] = 2,
    ACTIONS(365), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(363), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1754] = 2,
    ACTIONS(369), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(367), 8,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1770] = 4,
    ACTIONS(271), 1,
      anon_sym_DOT,
    ACTIONS(273), 1,
      anon_sym_LBRACK,
    ACTIONS(371), 1,
      anon_sym_STAR,
    ACTIONS(267), 5,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COLON,
  [1787] = 6,
    ACTIONS(271), 1,
      anon_sym_DOT,
    ACTIONS(273), 1,
      anon_sym_LBRACK,
    ACTIONS(371), 1,
      anon_sym_STAR,
    ACTIONS(373), 1,
      anon_sym_SEMI,
    ACTIONS(375), 1,
      anon_sym_PLUS,
    ACTIONS(377), 1,
      anon_sym_COLON,
  [1806] = 5,
    ACTIONS(271), 1,
      anon_sym_DOT,
    ACTIONS(273), 1,
      anon_sym_LBRACK,
    ACTIONS(371), 1,
      anon_sym_STAR,
    ACTIONS(375), 1,
      anon_sym_PLUS,
    ACTIONS(379), 1,
      anon_sym_SEMI,
  [1822] = 5,
    ACTIONS(271), 1,
      anon_sym_DOT,
    ACTIONS(273), 1,
      anon_sym_LBRACK,
    ACTIONS(371), 1,
      anon_sym_STAR,
    ACTIONS(375), 1,
      anon_sym_PLUS,
    ACTIONS(377), 1,
      anon_sym_COLON,
  [1838] = 5,
    ACTIONS(271), 1,
      anon_sym_DOT,
    ACTIONS(273), 1,
      anon_sym_LBRACK,
    ACTIONS(371), 1,
      anon_sym_STAR,
    ACTIONS(375), 1,
      anon_sym_PLUS,
    ACTIONS(381), 1,
      anon_sym_SEMI,
  [1854] = 5,
    ACTIONS(271), 1,
      anon_sym_DOT,
    ACTIONS(273), 1,
      anon_sym_LBRACK,
    ACTIONS(371), 1,
      anon_sym_STAR,
    ACTIONS(375), 1,
      anon_sym_PLUS,
    ACTIONS(383), 1,
      anon_sym_RBRACK,
  [1870] = 5,
    ACTIONS(271), 1,
      anon_sym_DOT,
    ACTIONS(273), 1,
      anon_sym_LBRACK,
    ACTIONS(371), 1,
      anon_sym_STAR,
    ACTIONS(375), 1,
      anon_sym_PLUS,
    ACTIONS(385), 1,
      anon_sym_SEMI,
  [1886] = 5,
    ACTIONS(271), 1,
      anon_sym_DOT,
    ACTIONS(273), 1,
      anon_sym_LBRACK,
    ACTIONS(371), 1,
      anon_sym_STAR,
    ACTIONS(375), 1,
      anon_sym_PLUS,
    ACTIONS(387), 1,
      anon_sym_RPAREN,
  [1902] = 5,
    ACTIONS(271), 1,
      anon_sym_DOT,
    ACTIONS(273), 1,
      anon_sym_LBRACK,
    ACTIONS(371), 1,
      anon_sym_STAR,
    ACTIONS(375), 1,
      anon_sym_PLUS,
    ACTIONS(389), 1,
      anon_sym_SEMI,
  [1918] = 5,
    ACTIONS(271), 1,
      anon_sym_DOT,
    ACTIONS(273), 1,
      anon_sym_LBRACK,
    ACTIONS(371), 1,
      anon_sym_STAR,
    ACTIONS(373), 1,
      anon_sym_SEMI,
    ACTIONS(375), 1,
      anon_sym_PLUS,
  [1934] = 5,
    ACTIONS(271), 1,
      anon_sym_DOT,
    ACTIONS(273), 1,
      anon_sym_LBRACK,
    ACTIONS(371), 1,
      anon_sym_STAR,
    ACTIONS(375), 1,
      anon_sym_PLUS,
    ACTIONS(391), 1,
      anon_sym_SEMI,
  [1950] = 3,
    ACTIONS(393), 1,
      anon_sym_RPAREN,
    ACTIONS(395), 1,
      sym_identifier,
    STATE(81), 2,
      aux_sym__parameter_list,
      sym_parameter,
  [1961] = 4,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(397), 1,
      sym_identifier,
    STATE(44), 1,
      sym_function_call,
    STATE(86), 1,
      sym_function,
  [1974] = 3,
    ACTIONS(399), 1,
      anon_sym_RPAREN,
    ACTIONS(401), 1,
      sym_identifier,
    STATE(80), 2,
      aux_sym__parameter_list,
      sym_parameter,
  [1985] = 3,
    ACTIONS(395), 1,
      sym_identifier,
    ACTIONS(404), 1,
      anon_sym_RPAREN,
    STATE(80), 2,
      aux_sym__parameter_list,
      sym_parameter,
  [1996] = 3,
    ACTIONS(406), 1,
      anon_sym_LBRACE,
    STATE(35), 1,
      sym__block_statement,
    STATE(47), 1,
      sym_body,
  [2006] = 2,
    ACTIONS(410), 1,
      anon_sym_COMMA,
    ACTIONS(408), 2,
      anon_sym_RPAREN,
      sym_identifier,
  [2014] = 3,
    ACTIONS(412), 1,
      anon_sym_LBRACE,
    STATE(35), 1,
      sym__block_statement,
    STATE(47), 1,
      sym_body,
  [2024] = 2,
    ACTIONS(414), 1,
      anon_sym_LPAREN,
    STATE(82), 1,
      sym_parameters,
  [2031] = 2,
    ACTIONS(255), 1,
      anon_sym_LPAREN,
    STATE(38), 1,
      sym_arguments,
  [2038] = 2,
    ACTIONS(416), 1,
      anon_sym_DQUOTE,
    ACTIONS(418), 1,
      sym__string,
  [2045] = 2,
    ACTIONS(414), 1,
      anon_sym_LPAREN,
    STATE(84), 1,
      sym_parameters,
  [2052] = 1,
    ACTIONS(420), 2,
      anon_sym_RPAREN,
      sym_identifier,
  [2057] = 1,
    ACTIONS(422), 1,
      anon_sym_LBRACE,
  [2061] = 1,
    ACTIONS(424), 1,
      anon_sym_DQUOTE,
  [2065] = 1,
    ACTIONS(426), 1,
      anon_sym_EQ,
  [2069] = 1,
    ACTIONS(428), 1,
      anon_sym_LBRACE,
  [2073] = 1,
    ACTIONS(430), 1,
      sym_identifier,
  [2077] = 1,
    ACTIONS(432), 1,
      ts_builtin_sym_end,
  [2081] = 1,
    ACTIONS(434), 1,
      anon_sym_EQ,
  [2085] = 1,
    ACTIONS(436), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(12)] = 0,
  [SMALL_STATE(13)] = 52,
  [SMALL_STATE(14)] = 103,
  [SMALL_STATE(15)] = 154,
  [SMALL_STATE(16)] = 205,
  [SMALL_STATE(17)] = 256,
  [SMALL_STATE(18)] = 307,
  [SMALL_STATE(19)] = 358,
  [SMALL_STATE(20)] = 409,
  [SMALL_STATE(21)] = 453,
  [SMALL_STATE(22)] = 497,
  [SMALL_STATE(23)] = 541,
  [SMALL_STATE(24)] = 585,
  [SMALL_STATE(25)] = 629,
  [SMALL_STATE(26)] = 673,
  [SMALL_STATE(27)] = 717,
  [SMALL_STATE(28)] = 761,
  [SMALL_STATE(29)] = 805,
  [SMALL_STATE(30)] = 849,
  [SMALL_STATE(31)] = 893,
  [SMALL_STATE(32)] = 937,
  [SMALL_STATE(33)] = 981,
  [SMALL_STATE(34)] = 1010,
  [SMALL_STATE(35)] = 1035,
  [SMALL_STATE(36)] = 1059,
  [SMALL_STATE(37)] = 1087,
  [SMALL_STATE(38)] = 1115,
  [SMALL_STATE(39)] = 1139,
  [SMALL_STATE(40)] = 1163,
  [SMALL_STATE(41)] = 1187,
  [SMALL_STATE(42)] = 1211,
  [SMALL_STATE(43)] = 1235,
  [SMALL_STATE(44)] = 1259,
  [SMALL_STATE(45)] = 1283,
  [SMALL_STATE(46)] = 1307,
  [SMALL_STATE(47)] = 1331,
  [SMALL_STATE(48)] = 1355,
  [SMALL_STATE(49)] = 1379,
  [SMALL_STATE(50)] = 1403,
  [SMALL_STATE(51)] = 1427,
  [SMALL_STATE(52)] = 1451,
  [SMALL_STATE(53)] = 1476,
  [SMALL_STATE(54)] = 1500,
  [SMALL_STATE(55)] = 1522,
  [SMALL_STATE(56)] = 1550,
  [SMALL_STATE(57)] = 1581,
  [SMALL_STATE(58)] = 1611,
  [SMALL_STATE(59)] = 1629,
  [SMALL_STATE(60)] = 1647,
  [SMALL_STATE(61)] = 1665,
  [SMALL_STATE(62)] = 1683,
  [SMALL_STATE(63)] = 1701,
  [SMALL_STATE(64)] = 1719,
  [SMALL_STATE(65)] = 1737,
  [SMALL_STATE(66)] = 1754,
  [SMALL_STATE(67)] = 1770,
  [SMALL_STATE(68)] = 1787,
  [SMALL_STATE(69)] = 1806,
  [SMALL_STATE(70)] = 1822,
  [SMALL_STATE(71)] = 1838,
  [SMALL_STATE(72)] = 1854,
  [SMALL_STATE(73)] = 1870,
  [SMALL_STATE(74)] = 1886,
  [SMALL_STATE(75)] = 1902,
  [SMALL_STATE(76)] = 1918,
  [SMALL_STATE(77)] = 1934,
  [SMALL_STATE(78)] = 1950,
  [SMALL_STATE(79)] = 1961,
  [SMALL_STATE(80)] = 1974,
  [SMALL_STATE(81)] = 1985,
  [SMALL_STATE(82)] = 1996,
  [SMALL_STATE(83)] = 2006,
  [SMALL_STATE(84)] = 2014,
  [SMALL_STATE(85)] = 2024,
  [SMALL_STATE(86)] = 2031,
  [SMALL_STATE(87)] = 2038,
  [SMALL_STATE(88)] = 2045,
  [SMALL_STATE(89)] = 2052,
  [SMALL_STATE(90)] = 2057,
  [SMALL_STATE(91)] = 2061,
  [SMALL_STATE(92)] = 2065,
  [SMALL_STATE(93)] = 2069,
  [SMALL_STATE(94)] = 2073,
  [SMALL_STATE(95)] = 2077,
  [SMALL_STATE(96)] = 2081,
  [SMALL_STATE(97)] = 2085,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statement_list, 2), SHIFT_REPEAT(97),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__statement_list, 2), SHIFT_REPEAT(20),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statement_list, 2), SHIFT_REPEAT(88),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statement_list, 2), SHIFT_REPEAT(30),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__statement_list, 2), SHIFT_REPEAT(3),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__statement_list, 2),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__statement_list, 2), SHIFT_REPEAT(15),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__statement_list, 2), SHIFT_REPEAT(87),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__statement_list, 2), SHIFT_REPEAT(23),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__statement_list, 2), SHIFT_REPEAT(76),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statement_list, 2), SHIFT_REPEAT(76),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statement_list, 2), SHIFT_REPEAT(33),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [82] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [86] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(94),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(20),
  [92] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(88),
  [95] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(22),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(2),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(15),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(87),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(23),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(73),
  [113] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(73),
  [116] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(33),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [125] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__argument_list, 2), SHIFT_REPEAT(20),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__argument_list, 2),
  [130] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__argument_list, 2), SHIFT_REPEAT(85),
  [133] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__argument_list, 2), SHIFT_REPEAT(17),
  [136] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__argument_list, 2), SHIFT_REPEAT(15),
  [139] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__argument_list, 2), SHIFT_REPEAT(87),
  [142] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__argument_list, 2), SHIFT_REPEAT(27),
  [145] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__argument_list, 2), SHIFT_REPEAT(56),
  [148] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__argument_list, 2), SHIFT_REPEAT(56),
  [151] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__argument_list, 2), SHIFT_REPEAT(33),
  [154] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [164] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [178] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__kv_pairs, 2), SHIFT_REPEAT(20),
  [181] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__kv_pairs, 2), SHIFT_REPEAT(88),
  [184] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__kv_pairs, 2), SHIFT_REPEAT(17),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__kv_pairs, 2),
  [189] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__kv_pairs, 2), SHIFT_REPEAT(15),
  [192] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__kv_pairs, 2), SHIFT_REPEAT(87),
  [195] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__kv_pairs, 2), SHIFT_REPEAT(23),
  [198] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__kv_pairs, 2), SHIFT_REPEAT(70),
  [201] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__kv_pairs, 2), SHIFT_REPEAT(70),
  [204] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__kv_pairs, 2), SHIFT_REPEAT(33),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [211] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [215] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [219] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [223] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [227] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [235] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [239] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [243] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [247] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [251] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [257] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block_statement, 3),
  [261] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__block_statement, 3),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 1),
  [265] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body, 1),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3),
  [269] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2),
  [277] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 2),
  [281] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 2),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block_statement, 2),
  [285] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__block_statement, 2),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 3),
  [289] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arguments, 3),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hash_literal, 2),
  [293] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_hash_literal, 2),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_index_expression, 4),
  [297] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_index_expression, 4),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__grouped_expression, 3),
  [301] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__grouped_expression, 3),
  [303] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_call, 3),
  [305] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_method_call, 3),
  [307] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 2),
  [309] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arguments, 2),
  [311] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3),
  [313] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 3),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 3),
  [317] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 3),
  [319] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_literal, 3),
  [321] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_literal, 3),
  [323] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_literal, 2),
  [325] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_literal, 2),
  [327] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 2),
  [329] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 2),
  [331] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hash_literal, 3),
  [333] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_hash_literal, 3),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [339] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__argument, 1),
  [341] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__argument, 1),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [345] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_kv_pair, 3),
  [347] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_kv_pair, 3),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [351] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression_statement, 2),
  [353] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression_statement, 2),
  [355] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 3),
  [357] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 3),
  [359] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_statement, 5, .production_id = 1),
  [361] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_statement, 5, .production_id = 1),
  [363] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__argument, 2),
  [365] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__argument, 2),
  [367] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_kv_pair, 4),
  [369] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_kv_pair, 4),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [379] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [383] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [385] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [387] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [389] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [391] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [393] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [395] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [397] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [399] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__parameter_list, 2),
  [401] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__parameter_list, 2), SHIFT_REPEAT(83),
  [404] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [406] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [408] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 1),
  [410] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [412] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [414] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [416] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [418] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [420] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 2),
  [422] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 3),
  [424] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [426] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [428] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 2),
  [430] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [432] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [434] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [436] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_monkeylang(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
