#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 83
#define LARGE_STATE_COUNT 11
#define SYMBOL_COUNT 45
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_let = 1,
  anon_sym_EQ = 2,
  anon_sym_SEMI = 3,
  anon_sym_STAR = 4,
  anon_sym_PLUS = 5,
  anon_sym_LPAREN = 6,
  anon_sym_RPAREN = 7,
  anon_sym_fn = 8,
  anon_sym_COMMA = 9,
  anon_sym_return = 10,
  anon_sym_LBRACE = 11,
  anon_sym_RBRACE = 12,
  anon_sym_DOT = 13,
  anon_sym_LBRACK = 14,
  anon_sym_RBRACK = 15,
  anon_sym_DASH = 16,
  anon_sym_BANG = 17,
  sym_number = 18,
  sym_boolean = 19,
  sym_identifier = 20,
  sym_source_file = 21,
  sym__statement = 22,
  sym_let_statement = 23,
  sym__expression_statement = 24,
  sym__expression = 25,
  sym_binary_expression = 26,
  sym__grouped_expression = 27,
  sym_function = 28,
  sym_parameters = 29,
  aux_sym__parameter_list = 30,
  sym__parameter = 31,
  sym_body = 32,
  sym_return_statement = 33,
  sym__block_statement = 34,
  aux_sym__statement_list = 35,
  sym_function_call = 36,
  sym_method_call = 37,
  sym_arguments = 38,
  aux_sym__argument_list = 39,
  sym__argument = 40,
  sym_array_literal = 41,
  sym_index_expression = 42,
  sym_unary_expression = 43,
  aux_sym_source_file_repeat1 = 44,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [anon_sym_STAR] = "*",
  [anon_sym_PLUS] = "+",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_fn] = "fn",
  [anon_sym_COMMA] = ",",
  [anon_sym_return] = "return",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_DOT] = ".",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DASH] = "-",
  [anon_sym_BANG] = "!",
  [sym_number] = "number",
  [sym_boolean] = "boolean",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_let_statement] = "let_statement",
  [sym__expression_statement] = "_expression_statement",
  [sym__expression] = "_expression",
  [sym_binary_expression] = "binary_expression",
  [sym__grouped_expression] = "_grouped_expression",
  [sym_function] = "function",
  [sym_parameters] = "parameters",
  [aux_sym__parameter_list] = "_parameter_list",
  [sym__parameter] = "_parameter",
  [sym_body] = "body",
  [sym_return_statement] = "return_statement",
  [sym__block_statement] = "_block_statement",
  [aux_sym__statement_list] = "_statement_list",
  [sym_function_call] = "function_call",
  [sym_method_call] = "method_call",
  [sym_arguments] = "arguments",
  [aux_sym__argument_list] = "_argument_list",
  [sym__argument] = "_argument",
  [sym_array_literal] = "array_literal",
  [sym_index_expression] = "index_expression",
  [sym_unary_expression] = "unary_expression",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_BANG] = anon_sym_BANG,
  [sym_number] = sym_number,
  [sym_boolean] = sym_boolean,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_let_statement] = sym_let_statement,
  [sym__expression_statement] = sym__expression_statement,
  [sym__expression] = sym__expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym__grouped_expression] = sym__grouped_expression,
  [sym_function] = sym_function,
  [sym_parameters] = sym_parameters,
  [aux_sym__parameter_list] = aux_sym__parameter_list,
  [sym__parameter] = sym__parameter,
  [sym_body] = sym_body,
  [sym_return_statement] = sym_return_statement,
  [sym__block_statement] = sym__block_statement,
  [aux_sym__statement_list] = aux_sym__statement_list,
  [sym_function_call] = sym_function_call,
  [sym_method_call] = sym_method_call,
  [sym_arguments] = sym_arguments,
  [aux_sym__argument_list] = aux_sym__argument_list,
  [sym__argument] = sym__argument,
  [sym_array_literal] = sym_array_literal,
  [sym_index_expression] = sym_index_expression,
  [sym_unary_expression] = sym_unary_expression,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_let_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression_statement] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__grouped_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_parameters] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__parameter_list] = {
    .visible = false,
    .named = false,
  },
  [sym__parameter] = {
    .visible = false,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__block_statement] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__statement_list] = {
    .visible = false,
    .named = false,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_method_call] = {
    .visible = true,
    .named = true,
  },
  [sym_arguments] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__argument_list] = {
    .visible = false,
    .named = false,
  },
  [sym__argument] = {
    .visible = false,
    .named = true,
  },
  [sym_array_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_index_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 2,
  [7] = 7,
  [8] = 5,
  [9] = 2,
  [10] = 5,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 16,
  [21] = 21,
  [22] = 22,
  [23] = 21,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 17,
  [28] = 24,
  [29] = 19,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 25,
  [47] = 18,
  [48] = 18,
  [49] = 49,
  [50] = 50,
  [51] = 49,
  [52] = 52,
  [53] = 25,
  [54] = 50,
  [55] = 52,
  [56] = 56,
  [57] = 36,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 58,
  [62] = 62,
  [63] = 60,
  [64] = 64,
  [65] = 64,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 70,
  [73] = 73,
  [74] = 74,
  [75] = 74,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 78,
  [82] = 76,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      if (lookahead == '!') ADVANCE(20);
      if (lookahead == '(') ADVANCE(9);
      if (lookahead == ')') ADVANCE(10);
      if (lookahead == '*') ADVANCE(7);
      if (lookahead == '+') ADVANCE(8);
      if (lookahead == ',') ADVANCE(12);
      if (lookahead == '-') ADVANCE(19);
      if (lookahead == '.') ADVANCE(16);
      if (lookahead == ';') ADVANCE(6);
      if (lookahead == '=') ADVANCE(5);
      if (lookahead == '[') ADVANCE(17);
      if (lookahead == ']') ADVANCE(18);
      if (lookahead == 'f') ADVANCE(23);
      if (lookahead == 'l') ADVANCE(24);
      if (lookahead == 'r') ADVANCE(26);
      if (lookahead == 't') ADVANCE(29);
      if (lookahead == '{') ADVANCE(14);
      if (lookahead == '}') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(20);
      if (lookahead == '(') ADVANCE(9);
      if (lookahead == ')') ADVANCE(10);
      if (lookahead == '*') ADVANCE(7);
      if (lookahead == '+') ADVANCE(8);
      if (lookahead == ',') ADVANCE(12);
      if (lookahead == '-') ADVANCE(19);
      if (lookahead == '.') ADVANCE(16);
      if (lookahead == ';') ADVANCE(6);
      if (lookahead == '[') ADVANCE(17);
      if (lookahead == ']') ADVANCE(18);
      if (lookahead == 'f') ADVANCE(23);
      if (lookahead == 't') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 2:
      if (lookahead == ')') ADVANCE(10);
      if (lookahead == ',') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_let);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_fn);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_return);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_boolean);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(27);
      if (lookahead == 'n') ADVANCE(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(31);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(34);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(35);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(30);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 2},
  [68] = {.lex_state = 2},
  [69] = {.lex_state = 2},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 2},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 2},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 2},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_boolean] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(80),
    [sym__statement] = STATE(7),
    [sym_let_statement] = STATE(7),
    [sym__expression_statement] = STATE(7),
    [sym__expression] = STATE(61),
    [sym_binary_expression] = STATE(61),
    [sym__grouped_expression] = STATE(61),
    [sym_function] = STATE(61),
    [sym_return_statement] = STATE(7),
    [sym__block_statement] = STATE(7),
    [sym_function_call] = STATE(61),
    [sym_method_call] = STATE(61),
    [sym_array_literal] = STATE(61),
    [sym_index_expression] = STATE(61),
    [sym_unary_expression] = STATE(61),
    [aux_sym_source_file_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_let] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_BANG] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [sym_boolean] = ACTIONS(21),
    [sym_identifier] = ACTIONS(23),
  },
  [2] = {
    [sym__statement] = STATE(3),
    [sym_let_statement] = STATE(3),
    [sym__expression_statement] = STATE(3),
    [sym__expression] = STATE(58),
    [sym_binary_expression] = STATE(58),
    [sym__grouped_expression] = STATE(58),
    [sym_function] = STATE(58),
    [sym_return_statement] = STATE(3),
    [sym__block_statement] = STATE(3),
    [aux_sym__statement_list] = STATE(3),
    [sym_function_call] = STATE(58),
    [sym_method_call] = STATE(58),
    [sym_array_literal] = STATE(58),
    [sym_index_expression] = STATE(58),
    [sym_unary_expression] = STATE(58),
    [anon_sym_let] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(29),
    [anon_sym_RBRACE] = ACTIONS(31),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_BANG] = ACTIONS(17),
    [sym_number] = ACTIONS(33),
    [sym_boolean] = ACTIONS(35),
    [sym_identifier] = ACTIONS(23),
  },
  [3] = {
    [sym__statement] = STATE(3),
    [sym_let_statement] = STATE(3),
    [sym__expression_statement] = STATE(3),
    [sym__expression] = STATE(58),
    [sym_binary_expression] = STATE(58),
    [sym__grouped_expression] = STATE(58),
    [sym_function] = STATE(58),
    [sym_return_statement] = STATE(3),
    [sym__block_statement] = STATE(3),
    [aux_sym__statement_list] = STATE(3),
    [sym_function_call] = STATE(58),
    [sym_method_call] = STATE(58),
    [sym_array_literal] = STATE(58),
    [sym_index_expression] = STATE(58),
    [sym_unary_expression] = STATE(58),
    [anon_sym_let] = ACTIONS(37),
    [anon_sym_LPAREN] = ACTIONS(40),
    [anon_sym_fn] = ACTIONS(43),
    [anon_sym_return] = ACTIONS(46),
    [anon_sym_LBRACE] = ACTIONS(49),
    [anon_sym_RBRACE] = ACTIONS(52),
    [anon_sym_LBRACK] = ACTIONS(54),
    [anon_sym_DASH] = ACTIONS(57),
    [anon_sym_BANG] = ACTIONS(57),
    [sym_number] = ACTIONS(60),
    [sym_boolean] = ACTIONS(63),
    [sym_identifier] = ACTIONS(66),
  },
  [4] = {
    [sym__statement] = STATE(4),
    [sym_let_statement] = STATE(4),
    [sym__expression_statement] = STATE(4),
    [sym__expression] = STATE(61),
    [sym_binary_expression] = STATE(61),
    [sym__grouped_expression] = STATE(61),
    [sym_function] = STATE(61),
    [sym_return_statement] = STATE(4),
    [sym__block_statement] = STATE(4),
    [sym_function_call] = STATE(61),
    [sym_method_call] = STATE(61),
    [sym_array_literal] = STATE(61),
    [sym_index_expression] = STATE(61),
    [sym_unary_expression] = STATE(61),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(69),
    [anon_sym_let] = ACTIONS(71),
    [anon_sym_LPAREN] = ACTIONS(74),
    [anon_sym_fn] = ACTIONS(77),
    [anon_sym_return] = ACTIONS(80),
    [anon_sym_LBRACE] = ACTIONS(83),
    [anon_sym_LBRACK] = ACTIONS(86),
    [anon_sym_DASH] = ACTIONS(89),
    [anon_sym_BANG] = ACTIONS(89),
    [sym_number] = ACTIONS(92),
    [sym_boolean] = ACTIONS(95),
    [sym_identifier] = ACTIONS(98),
  },
  [5] = {
    [sym__statement] = STATE(6),
    [sym_let_statement] = STATE(6),
    [sym__expression_statement] = STATE(6),
    [sym__expression] = STATE(58),
    [sym_binary_expression] = STATE(58),
    [sym__grouped_expression] = STATE(58),
    [sym_function] = STATE(58),
    [sym_return_statement] = STATE(6),
    [sym__block_statement] = STATE(6),
    [aux_sym__statement_list] = STATE(6),
    [sym_function_call] = STATE(58),
    [sym_method_call] = STATE(58),
    [sym_array_literal] = STATE(58),
    [sym_index_expression] = STATE(58),
    [sym_unary_expression] = STATE(58),
    [anon_sym_let] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(29),
    [anon_sym_RBRACE] = ACTIONS(101),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_BANG] = ACTIONS(17),
    [sym_number] = ACTIONS(33),
    [sym_boolean] = ACTIONS(35),
    [sym_identifier] = ACTIONS(23),
  },
  [6] = {
    [sym__statement] = STATE(3),
    [sym_let_statement] = STATE(3),
    [sym__expression_statement] = STATE(3),
    [sym__expression] = STATE(58),
    [sym_binary_expression] = STATE(58),
    [sym__grouped_expression] = STATE(58),
    [sym_function] = STATE(58),
    [sym_return_statement] = STATE(3),
    [sym__block_statement] = STATE(3),
    [aux_sym__statement_list] = STATE(3),
    [sym_function_call] = STATE(58),
    [sym_method_call] = STATE(58),
    [sym_array_literal] = STATE(58),
    [sym_index_expression] = STATE(58),
    [sym_unary_expression] = STATE(58),
    [anon_sym_let] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(29),
    [anon_sym_RBRACE] = ACTIONS(103),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_BANG] = ACTIONS(17),
    [sym_number] = ACTIONS(33),
    [sym_boolean] = ACTIONS(35),
    [sym_identifier] = ACTIONS(23),
  },
  [7] = {
    [sym__statement] = STATE(4),
    [sym_let_statement] = STATE(4),
    [sym__expression_statement] = STATE(4),
    [sym__expression] = STATE(61),
    [sym_binary_expression] = STATE(61),
    [sym__grouped_expression] = STATE(61),
    [sym_function] = STATE(61),
    [sym_return_statement] = STATE(4),
    [sym__block_statement] = STATE(4),
    [sym_function_call] = STATE(61),
    [sym_method_call] = STATE(61),
    [sym_array_literal] = STATE(61),
    [sym_index_expression] = STATE(61),
    [sym_unary_expression] = STATE(61),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(105),
    [anon_sym_let] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_BANG] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [sym_boolean] = ACTIONS(21),
    [sym_identifier] = ACTIONS(23),
  },
  [8] = {
    [sym__statement] = STATE(2),
    [sym_let_statement] = STATE(2),
    [sym__expression_statement] = STATE(2),
    [sym__expression] = STATE(58),
    [sym_binary_expression] = STATE(58),
    [sym__grouped_expression] = STATE(58),
    [sym_function] = STATE(58),
    [sym_return_statement] = STATE(2),
    [sym__block_statement] = STATE(2),
    [aux_sym__statement_list] = STATE(2),
    [sym_function_call] = STATE(58),
    [sym_method_call] = STATE(58),
    [sym_array_literal] = STATE(58),
    [sym_index_expression] = STATE(58),
    [sym_unary_expression] = STATE(58),
    [anon_sym_let] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(29),
    [anon_sym_RBRACE] = ACTIONS(107),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_BANG] = ACTIONS(17),
    [sym_number] = ACTIONS(33),
    [sym_boolean] = ACTIONS(35),
    [sym_identifier] = ACTIONS(23),
  },
  [9] = {
    [sym__statement] = STATE(3),
    [sym_let_statement] = STATE(3),
    [sym__expression_statement] = STATE(3),
    [sym__expression] = STATE(58),
    [sym_binary_expression] = STATE(58),
    [sym__grouped_expression] = STATE(58),
    [sym_function] = STATE(58),
    [sym_return_statement] = STATE(3),
    [sym__block_statement] = STATE(3),
    [aux_sym__statement_list] = STATE(3),
    [sym_function_call] = STATE(58),
    [sym_method_call] = STATE(58),
    [sym_array_literal] = STATE(58),
    [sym_index_expression] = STATE(58),
    [sym_unary_expression] = STATE(58),
    [anon_sym_let] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(29),
    [anon_sym_RBRACE] = ACTIONS(109),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_BANG] = ACTIONS(17),
    [sym_number] = ACTIONS(33),
    [sym_boolean] = ACTIONS(35),
    [sym_identifier] = ACTIONS(23),
  },
  [10] = {
    [sym__statement] = STATE(9),
    [sym_let_statement] = STATE(9),
    [sym__expression_statement] = STATE(9),
    [sym__expression] = STATE(58),
    [sym_binary_expression] = STATE(58),
    [sym__grouped_expression] = STATE(58),
    [sym_function] = STATE(58),
    [sym_return_statement] = STATE(9),
    [sym__block_statement] = STATE(9),
    [aux_sym__statement_list] = STATE(9),
    [sym_function_call] = STATE(58),
    [sym_method_call] = STATE(58),
    [sym_array_literal] = STATE(58),
    [sym_index_expression] = STATE(58),
    [sym_unary_expression] = STATE(58),
    [anon_sym_let] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(29),
    [anon_sym_RBRACE] = ACTIONS(111),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_BANG] = ACTIONS(17),
    [sym_number] = ACTIONS(33),
    [sym_boolean] = ACTIONS(35),
    [sym_identifier] = ACTIONS(23),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(113), 1,
      anon_sym_LPAREN,
    ACTIONS(118), 1,
      anon_sym_fn,
    ACTIONS(121), 1,
      anon_sym_LBRACK,
    ACTIONS(127), 1,
      sym_number,
    ACTIONS(130), 1,
      sym_boolean,
    ACTIONS(133), 1,
      sym_identifier,
    ACTIONS(116), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
    ACTIONS(124), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(11), 2,
      aux_sym__argument_list,
      sym__argument,
    STATE(37), 9,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_method_call,
      sym_array_literal,
      sym_index_expression,
      sym_unary_expression,
  [42] = 10,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(136), 1,
      anon_sym_RPAREN,
    ACTIONS(138), 1,
      anon_sym_fn,
    ACTIONS(142), 1,
      sym_number,
    ACTIONS(144), 1,
      sym_boolean,
    ACTIONS(140), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(15), 2,
      aux_sym__argument_list,
      sym__argument,
    STATE(37), 9,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_method_call,
      sym_array_literal,
      sym_index_expression,
      sym_unary_expression,
  [83] = 10,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(138), 1,
      anon_sym_fn,
    ACTIONS(142), 1,
      sym_number,
    ACTIONS(144), 1,
      sym_boolean,
    ACTIONS(146), 1,
      anon_sym_RBRACK,
    ACTIONS(140), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(14), 2,
      aux_sym__argument_list,
      sym__argument,
    STATE(37), 9,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_method_call,
      sym_array_literal,
      sym_index_expression,
      sym_unary_expression,
  [124] = 10,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(138), 1,
      anon_sym_fn,
    ACTIONS(142), 1,
      sym_number,
    ACTIONS(144), 1,
      sym_boolean,
    ACTIONS(148), 1,
      anon_sym_RBRACK,
    ACTIONS(140), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(11), 2,
      aux_sym__argument_list,
      sym__argument,
    STATE(37), 9,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_method_call,
      sym_array_literal,
      sym_index_expression,
      sym_unary_expression,
  [165] = 10,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(138), 1,
      anon_sym_fn,
    ACTIONS(142), 1,
      sym_number,
    ACTIONS(144), 1,
      sym_boolean,
    ACTIONS(150), 1,
      anon_sym_RPAREN,
    ACTIONS(140), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(11), 2,
      aux_sym__argument_list,
      sym__argument,
    STATE(37), 9,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_method_call,
      sym_array_literal,
      sym_index_expression,
      sym_unary_expression,
  [206] = 8,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(152), 1,
      sym_number,
    ACTIONS(154), 1,
      sym_boolean,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(32), 9,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_method_call,
      sym_array_literal,
      sym_index_expression,
      sym_unary_expression,
  [240] = 8,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(156), 1,
      sym_number,
    ACTIONS(158), 1,
      sym_boolean,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(65), 9,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_method_call,
      sym_array_literal,
      sym_index_expression,
      sym_unary_expression,
  [274] = 2,
    ACTIONS(162), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(160), 12,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [296] = 8,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(164), 1,
      sym_number,
    ACTIONS(166), 1,
      sym_boolean,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(63), 9,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_method_call,
      sym_array_literal,
      sym_index_expression,
      sym_unary_expression,
  [330] = 8,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(138), 1,
      anon_sym_fn,
    ACTIONS(152), 1,
      sym_number,
    ACTIONS(154), 1,
      sym_boolean,
    ACTIONS(140), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(32), 9,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_method_call,
      sym_array_literal,
      sym_index_expression,
      sym_unary_expression,
  [364] = 8,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(138), 1,
      anon_sym_fn,
    ACTIONS(168), 1,
      sym_number,
    ACTIONS(170), 1,
      sym_boolean,
    ACTIONS(140), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(33), 9,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_method_call,
      sym_array_literal,
      sym_index_expression,
      sym_unary_expression,
  [398] = 9,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(172), 1,
      sym_number,
    ACTIONS(174), 1,
      sym_boolean,
    STATE(44), 1,
      sym_function_call,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(66), 8,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_method_call,
      sym_array_literal,
      sym_index_expression,
      sym_unary_expression,
  [434] = 8,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(168), 1,
      sym_number,
    ACTIONS(170), 1,
      sym_boolean,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(33), 9,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_method_call,
      sym_array_literal,
      sym_index_expression,
      sym_unary_expression,
  [468] = 8,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(176), 1,
      sym_number,
    ACTIONS(178), 1,
      sym_boolean,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(57), 9,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_method_call,
      sym_array_literal,
      sym_index_expression,
      sym_unary_expression,
  [502] = 2,
    ACTIONS(182), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(180), 12,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [524] = 8,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(184), 1,
      sym_number,
    ACTIONS(186), 1,
      sym_boolean,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(59), 9,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_method_call,
      sym_array_literal,
      sym_index_expression,
      sym_unary_expression,
  [558] = 8,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(188), 1,
      sym_number,
    ACTIONS(190), 1,
      sym_boolean,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(64), 9,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_method_call,
      sym_array_literal,
      sym_index_expression,
      sym_unary_expression,
  [592] = 8,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(138), 1,
      anon_sym_fn,
    ACTIONS(192), 1,
      sym_number,
    ACTIONS(194), 1,
      sym_boolean,
    ACTIONS(140), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(36), 9,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_method_call,
      sym_array_literal,
      sym_index_expression,
      sym_unary_expression,
  [626] = 8,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(196), 1,
      sym_number,
    ACTIONS(198), 1,
      sym_boolean,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(60), 9,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_method_call,
      sym_array_literal,
      sym_index_expression,
      sym_unary_expression,
  [660] = 8,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(200), 1,
      sym_number,
    ACTIONS(202), 1,
      sym_boolean,
    ACTIONS(17), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(62), 9,
      sym__expression,
      sym_binary_expression,
      sym__grouped_expression,
      sym_function,
      sym_function_call,
      sym_method_call,
      sym_array_literal,
      sym_index_expression,
      sym_unary_expression,
  [694] = 3,
    ACTIONS(208), 1,
      anon_sym_DOT,
    ACTIONS(206), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(204), 11,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [716] = 5,
    ACTIONS(212), 1,
      anon_sym_LPAREN,
    ACTIONS(216), 1,
      anon_sym_LBRACK,
    STATE(45), 1,
      sym_arguments,
    ACTIONS(214), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(210), 9,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [742] = 5,
    ACTIONS(212), 1,
      anon_sym_LPAREN,
    ACTIONS(216), 1,
      anon_sym_LBRACK,
    STATE(45), 1,
      sym_arguments,
    ACTIONS(220), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(218), 9,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [768] = 2,
    ACTIONS(224), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(222), 11,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [787] = 2,
    ACTIONS(228), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(226), 11,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [806] = 6,
    ACTIONS(212), 1,
      anon_sym_LPAREN,
    ACTIONS(216), 1,
      anon_sym_LBRACK,
    ACTIONS(230), 1,
      anon_sym_STAR,
    STATE(45), 1,
      sym_arguments,
    ACTIONS(220), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(218), 7,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [833] = 8,
    ACTIONS(212), 1,
      anon_sym_LPAREN,
    ACTIONS(216), 1,
      anon_sym_LBRACK,
    ACTIONS(230), 1,
      anon_sym_STAR,
    ACTIONS(232), 1,
      anon_sym_PLUS,
    ACTIONS(238), 1,
      anon_sym_COMMA,
    STATE(45), 1,
      sym_arguments,
    ACTIONS(236), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(234), 5,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [864] = 2,
    ACTIONS(242), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(240), 11,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [883] = 2,
    ACTIONS(246), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(244), 11,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [902] = 2,
    ACTIONS(250), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(248), 11,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [921] = 2,
    ACTIONS(254), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(252), 11,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [940] = 2,
    ACTIONS(258), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(256), 11,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [959] = 2,
    ACTIONS(262), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(260), 11,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [978] = 2,
    ACTIONS(266), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(264), 11,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [997] = 2,
    ACTIONS(270), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(268), 11,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1016] = 2,
    ACTIONS(182), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(180), 10,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1034] = 2,
    ACTIONS(162), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(160), 10,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1052] = 2,
    ACTIONS(162), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(160), 7,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1069] = 2,
    ACTIONS(274), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(272), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1086] = 2,
    ACTIONS(278), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(276), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1103] = 2,
    ACTIONS(274), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(272), 7,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1120] = 2,
    ACTIONS(280), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(282), 7,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1137] = 2,
    ACTIONS(182), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(180), 7,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1154] = 2,
    ACTIONS(278), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(276), 7,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1171] = 2,
    ACTIONS(280), 5,
      anon_sym_let,
      anon_sym_fn,
      anon_sym_return,
      sym_boolean,
      sym_identifier,
    ACTIONS(282), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1188] = 2,
    ACTIONS(286), 3,
      anon_sym_fn,
      sym_boolean,
      sym_identifier,
    ACTIONS(284), 7,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_number,
  [1203] = 5,
    ACTIONS(212), 1,
      anon_sym_LPAREN,
    ACTIONS(216), 1,
      anon_sym_LBRACK,
    ACTIONS(288), 1,
      anon_sym_STAR,
    STATE(45), 1,
      sym_arguments,
    ACTIONS(218), 4,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1222] = 6,
    ACTIONS(212), 1,
      anon_sym_LPAREN,
    ACTIONS(216), 1,
      anon_sym_LBRACK,
    ACTIONS(288), 1,
      anon_sym_STAR,
    ACTIONS(290), 1,
      anon_sym_SEMI,
    ACTIONS(292), 1,
      anon_sym_PLUS,
    STATE(45), 1,
      sym_arguments,
  [1241] = 6,
    ACTIONS(212), 1,
      anon_sym_LPAREN,
    ACTIONS(216), 1,
      anon_sym_LBRACK,
    ACTIONS(288), 1,
      anon_sym_STAR,
    ACTIONS(292), 1,
      anon_sym_PLUS,
    ACTIONS(294), 1,
      anon_sym_RBRACK,
    STATE(45), 1,
      sym_arguments,
  [1260] = 6,
    ACTIONS(212), 1,
      anon_sym_LPAREN,
    ACTIONS(216), 1,
      anon_sym_LBRACK,
    ACTIONS(288), 1,
      anon_sym_STAR,
    ACTIONS(292), 1,
      anon_sym_PLUS,
    ACTIONS(296), 1,
      anon_sym_SEMI,
    STATE(45), 1,
      sym_arguments,
  [1279] = 6,
    ACTIONS(212), 1,
      anon_sym_LPAREN,
    ACTIONS(216), 1,
      anon_sym_LBRACK,
    ACTIONS(288), 1,
      anon_sym_STAR,
    ACTIONS(292), 1,
      anon_sym_PLUS,
    ACTIONS(298), 1,
      anon_sym_SEMI,
    STATE(45), 1,
      sym_arguments,
  [1298] = 6,
    ACTIONS(212), 1,
      anon_sym_LPAREN,
    ACTIONS(216), 1,
      anon_sym_LBRACK,
    ACTIONS(288), 1,
      anon_sym_STAR,
    ACTIONS(292), 1,
      anon_sym_PLUS,
    ACTIONS(300), 1,
      anon_sym_RPAREN,
    STATE(45), 1,
      sym_arguments,
  [1317] = 6,
    ACTIONS(212), 1,
      anon_sym_LPAREN,
    ACTIONS(216), 1,
      anon_sym_LBRACK,
    ACTIONS(288), 1,
      anon_sym_STAR,
    ACTIONS(292), 1,
      anon_sym_PLUS,
    ACTIONS(302), 1,
      anon_sym_SEMI,
    STATE(45), 1,
      sym_arguments,
  [1336] = 6,
    ACTIONS(212), 1,
      anon_sym_LPAREN,
    ACTIONS(216), 1,
      anon_sym_LBRACK,
    ACTIONS(288), 1,
      anon_sym_STAR,
    ACTIONS(292), 1,
      anon_sym_PLUS,
    ACTIONS(304), 1,
      anon_sym_SEMI,
    STATE(45), 1,
      sym_arguments,
  [1355] = 6,
    ACTIONS(212), 1,
      anon_sym_LPAREN,
    ACTIONS(216), 1,
      anon_sym_LBRACK,
    ACTIONS(288), 1,
      anon_sym_STAR,
    ACTIONS(292), 1,
      anon_sym_PLUS,
    ACTIONS(306), 1,
      anon_sym_SEMI,
    STATE(45), 1,
      sym_arguments,
  [1374] = 5,
    ACTIONS(212), 1,
      anon_sym_LPAREN,
    ACTIONS(216), 1,
      anon_sym_LBRACK,
    ACTIONS(288), 1,
      anon_sym_STAR,
    ACTIONS(292), 1,
      anon_sym_PLUS,
    STATE(45), 1,
      sym_arguments,
  [1390] = 3,
    ACTIONS(308), 1,
      anon_sym_RPAREN,
    ACTIONS(310), 1,
      sym_identifier,
    STATE(69), 2,
      aux_sym__parameter_list,
      sym__parameter,
  [1401] = 3,
    ACTIONS(312), 1,
      anon_sym_RPAREN,
    ACTIONS(314), 1,
      sym_identifier,
    STATE(68), 2,
      aux_sym__parameter_list,
      sym__parameter,
  [1412] = 3,
    ACTIONS(310), 1,
      sym_identifier,
    ACTIONS(317), 1,
      anon_sym_RPAREN,
    STATE(68), 2,
      aux_sym__parameter_list,
      sym__parameter,
  [1423] = 3,
    ACTIONS(319), 1,
      anon_sym_LBRACE,
    STATE(38), 1,
      sym_body,
    STATE(39), 1,
      sym__block_statement,
  [1433] = 2,
    ACTIONS(323), 1,
      anon_sym_COMMA,
    ACTIONS(321), 2,
      anon_sym_RPAREN,
      sym_identifier,
  [1441] = 3,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    STATE(38), 1,
      sym_body,
    STATE(39), 1,
      sym__block_statement,
  [1451] = 1,
    ACTIONS(325), 2,
      anon_sym_RPAREN,
      sym_identifier,
  [1456] = 2,
    ACTIONS(327), 1,
      anon_sym_LPAREN,
    STATE(70), 1,
      sym_parameters,
  [1463] = 2,
    ACTIONS(327), 1,
      anon_sym_LPAREN,
    STATE(72), 1,
      sym_parameters,
  [1470] = 1,
    ACTIONS(329), 1,
      sym_identifier,
  [1474] = 1,
    ACTIONS(331), 1,
      anon_sym_LBRACE,
  [1478] = 1,
    ACTIONS(333), 1,
      anon_sym_EQ,
  [1482] = 1,
    ACTIONS(335), 1,
      anon_sym_LBRACE,
  [1486] = 1,
    ACTIONS(337), 1,
      ts_builtin_sym_end,
  [1490] = 1,
    ACTIONS(339), 1,
      anon_sym_EQ,
  [1494] = 1,
    ACTIONS(341), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(11)] = 0,
  [SMALL_STATE(12)] = 42,
  [SMALL_STATE(13)] = 83,
  [SMALL_STATE(14)] = 124,
  [SMALL_STATE(15)] = 165,
  [SMALL_STATE(16)] = 206,
  [SMALL_STATE(17)] = 240,
  [SMALL_STATE(18)] = 274,
  [SMALL_STATE(19)] = 296,
  [SMALL_STATE(20)] = 330,
  [SMALL_STATE(21)] = 364,
  [SMALL_STATE(22)] = 398,
  [SMALL_STATE(23)] = 434,
  [SMALL_STATE(24)] = 468,
  [SMALL_STATE(25)] = 502,
  [SMALL_STATE(26)] = 524,
  [SMALL_STATE(27)] = 558,
  [SMALL_STATE(28)] = 592,
  [SMALL_STATE(29)] = 626,
  [SMALL_STATE(30)] = 660,
  [SMALL_STATE(31)] = 694,
  [SMALL_STATE(32)] = 716,
  [SMALL_STATE(33)] = 742,
  [SMALL_STATE(34)] = 768,
  [SMALL_STATE(35)] = 787,
  [SMALL_STATE(36)] = 806,
  [SMALL_STATE(37)] = 833,
  [SMALL_STATE(38)] = 864,
  [SMALL_STATE(39)] = 883,
  [SMALL_STATE(40)] = 902,
  [SMALL_STATE(41)] = 921,
  [SMALL_STATE(42)] = 940,
  [SMALL_STATE(43)] = 959,
  [SMALL_STATE(44)] = 978,
  [SMALL_STATE(45)] = 997,
  [SMALL_STATE(46)] = 1016,
  [SMALL_STATE(47)] = 1034,
  [SMALL_STATE(48)] = 1052,
  [SMALL_STATE(49)] = 1069,
  [SMALL_STATE(50)] = 1086,
  [SMALL_STATE(51)] = 1103,
  [SMALL_STATE(52)] = 1120,
  [SMALL_STATE(53)] = 1137,
  [SMALL_STATE(54)] = 1154,
  [SMALL_STATE(55)] = 1171,
  [SMALL_STATE(56)] = 1188,
  [SMALL_STATE(57)] = 1203,
  [SMALL_STATE(58)] = 1222,
  [SMALL_STATE(59)] = 1241,
  [SMALL_STATE(60)] = 1260,
  [SMALL_STATE(61)] = 1279,
  [SMALL_STATE(62)] = 1298,
  [SMALL_STATE(63)] = 1317,
  [SMALL_STATE(64)] = 1336,
  [SMALL_STATE(65)] = 1355,
  [SMALL_STATE(66)] = 1374,
  [SMALL_STATE(67)] = 1390,
  [SMALL_STATE(68)] = 1401,
  [SMALL_STATE(69)] = 1412,
  [SMALL_STATE(70)] = 1423,
  [SMALL_STATE(71)] = 1433,
  [SMALL_STATE(72)] = 1441,
  [SMALL_STATE(73)] = 1451,
  [SMALL_STATE(74)] = 1456,
  [SMALL_STATE(75)] = 1463,
  [SMALL_STATE(76)] = 1470,
  [SMALL_STATE(77)] = 1474,
  [SMALL_STATE(78)] = 1478,
  [SMALL_STATE(79)] = 1482,
  [SMALL_STATE(80)] = 1486,
  [SMALL_STATE(81)] = 1490,
  [SMALL_STATE(82)] = 1494,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statement_list, 2), SHIFT_REPEAT(82),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__statement_list, 2), SHIFT_REPEAT(30),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statement_list, 2), SHIFT_REPEAT(75),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statement_list, 2), SHIFT_REPEAT(17),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__statement_list, 2), SHIFT_REPEAT(8),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__statement_list, 2),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__statement_list, 2), SHIFT_REPEAT(13),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__statement_list, 2), SHIFT_REPEAT(16),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__statement_list, 2), SHIFT_REPEAT(58),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statement_list, 2), SHIFT_REPEAT(58),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statement_list, 2), SHIFT_REPEAT(31),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [71] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(76),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(30),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(75),
  [80] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(27),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(5),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(13),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(16),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(61),
  [95] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(61),
  [98] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(31),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [113] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__argument_list, 2), SHIFT_REPEAT(30),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__argument_list, 2),
  [118] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__argument_list, 2), SHIFT_REPEAT(74),
  [121] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__argument_list, 2), SHIFT_REPEAT(13),
  [124] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__argument_list, 2), SHIFT_REPEAT(20),
  [127] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__argument_list, 2), SHIFT_REPEAT(37),
  [130] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__argument_list, 2), SHIFT_REPEAT(37),
  [133] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__argument_list, 2), SHIFT_REPEAT(31),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [154] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [158] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block_statement, 2),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__block_statement, 2),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block_statement, 3),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__block_statement, 3),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [190] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [194] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [198] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [202] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [206] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [214] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_literal, 2),
  [224] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_literal, 2),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_index_expression, 4),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_index_expression, 4),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__argument, 1),
  [236] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__argument, 1),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 3),
  [242] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 3),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 1),
  [246] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body, 1),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 2),
  [250] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arguments, 2),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_literal, 3),
  [254] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_literal, 3),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__grouped_expression, 3),
  [258] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__grouped_expression, 3),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 3),
  [262] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arguments, 3),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_call, 3),
  [266] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_method_call, 3),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 2),
  [270] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 2),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression_statement, 2),
  [274] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression_statement, 2),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_statement, 5),
  [278] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_statement, 5),
  [280] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 3),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 3),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__argument, 2),
  [286] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__argument, 2),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__parameter_list, 2),
  [314] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__parameter_list, 2), SHIFT_REPEAT(71),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [321] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parameter, 1),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [325] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parameter, 2),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [331] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 2),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [335] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 3),
  [337] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_monkeylang(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
